<div class="modal fade bd-example-modal-lg" id="ModalView" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Information </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="row text-center">
                    <div class="col-md-12  mb-2 p-1" id="img">
                        
                    </div>
                    <div class="col-md-12 text-center mb-1" id="title">

                    </div>
                    <div class="col-md-12 p-1 mb-1">
                        <p id="description"></p>
                    </div>
                    <p class="h5 mt-3"><strong>Category</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="category_id_view">
                        
                    </div>
                    <div class="col-md-12 p-1 mb-1" id="Links">
                        
                    </div>

                    <!-- <p class="h5 mt-3"><strong>Award Section</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="award_section">
                        
                    </div> -->

                    <p class="h5 mt-3"><strong>Guests</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="guest">
                        
                    </div>

                    <p class="h5 mt-3"><strong>Roles</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="role">
                        
                    </div>

                    <p class="h5 mt-3"><strong>Video Link</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="video_link_div">
                        
                    </div>
                    
                    <p class="h5 mt-3"><strong>Photographer Name</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="photographer_name_div">
                        
                    </div>

                    <p class="h5 mt-3"><strong>Description</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="description_div">
                        
                    </div>

                    <p class="h5 mt-3"><strong>Tags</strong></p>
                    <div class="col-md-12 p-1 mb-1" id="tags_div">
                        
                    </div>
                </div>
   
            </div>
            <div class="modal-footer-glass modal-footer">
            </div>
        </div>
    </div>
</div>