<?php

include_once $VIEW_PATH_ADMIN_INCLUDE . "modal/AddNote.phtml";


?>
<div class="covers m-top">

    <div class="covers  mb-3">

    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Files</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>