<?php
include_once($VIEW_PATH_ADMIN_INCLUDE . "BusinessUser/modal/AddUser.phtml");
include_once($VIEW_PATH_ADMIN_INCLUDE . "BusinessUser/modal/EditUser.phtml");
//include_once $VIEW_PATH_ADMIN_INCLUDE . "Common/modal/SendToTop.phtml";
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/Category.phtml";
include_once $VIEW_PATH_ADMIN_INCLUDE . "Common/modal/SendToHome.phtml";
include_once $VIEW_PATH_INCLUDE . "BusinessDashboard/modal/AddToTop.phtml";
include_once $VIEW_PATH_INCLUDE . "BusinessDashboard/Product/modal/EditImage.phtml";
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/Category.phtml";


?>
<div class="covers m-top">

    <div class="covers  mb-3">
        <form id="searchfrm">
            <div class="row">
                <div class="col-md-12 mb-2">
                    <small id="addNewBtn" class="btn btn-prim btn-lg ">
                        <i class="bi bi-plus-lg mr-2"></i> Add Business User
                    </small>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">ID:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Email:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="emails">
                    </div>
                </div>

                <div class="col-md-6">
                <label for="recipient-name" class="col-form-label">Type:</label>
                    <select class="form-control "  id="typeS">
                        <?php include $VIEW_PATH_INCLUDE . "Admin/BusinessUser/modal/Type.phtml"; ?>
                    </select>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Name:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="fnames">
                    </div>
                </div>


                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Category:</label>
                        <div data-dismiss="modal" type="text" class="form-control p-3 point" id="categorysearch_id"></div>
                        <input type="text" hidden class="form-control point" id="categorys_id">
                    </div>
                </div>

                <div class="col-md-12 mb-2 text-center">
                    <button type="button" id="searchbtn" class="btn btn-prim btn-lg">
                        <i class="bi bi-search mr-2"></i> Search
                    </button>
                    <button id="reset" type="button" class="btn  btn-lg">
                        Reset
                    </button>
                </div>
            </div>
        </form>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Type</th>
                <th>Category</th>
                <th>Activities</th>
                <th>Verify</th>
                <th>Top Show</th>
                <th>Home Show</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>