<link rel="stylesheet" href="<?= $VIEW_PATH ?>css/WebSite/Layout/Footer.css">

<footer>
    <div class="row contains-item-page">
        <div class="col-md-4">
            <span style="width: 100px;">

                <a class="hrefs" href="<?= $URL_Domain ?>"><?= $SiteName ?></a>

            </span>
        </div>
        <div class="col-md-4 ">
            <div class="mb-1">
                <h5>Useful links</h5>
            </div>

            <!-- <div class="mb-1 mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>RegisterBusiness"><small>Register Business Account</small></a>
            </div> -->
            <div class="mb-1 mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Help"><small>Help</small></a>
            </div>
            <div class="mb-1 mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Login"><small>Login</small></a>
            </div>
            <div class="mb-1 mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Register"><small>Register</small></a>
            </div>

            <div class="mb-1 mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Sponsorships"><small>Sponsorship</small></a>
            </div>
            <div class="mb-1 mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>About"><small>About us</small></a>
            </div>
            <div class="mb-1 mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>ContactWithUs"><small>Contact With us</small></a>
            </div>
        </div>
        <div class="col-md-4 ">
            <div class="">
                <h5>Menu</h5>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Products"><small>Products</small></a>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Prizes"><small>Prizes</small></a>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Coupons"><small>Coupons</small></a>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Deal"><small>Deals</small></a>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Programs"><small>Programs</small></a>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Winners"><small>Winners</small></a>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Jobs"><small>Jobs</small></a>
            </div>
            <div class=" mt-1 mb-1">
                <a class="text-muted" href="<?= $URL_Domain ?>Networks"><small>Networks</small></a>
            </div>
        </div>
  
    </div>
</footer>