


<footer class="main">
           
            <section class="section-padding footer-mid">
                <div class="container pt-15 pb-20">
                    <div class="row">
                        <div class="col">
                            <div class="widget-about font-md mb-md-3 mb-lg-3 mb-xl-0">
                                <div class="logo mb-30">
                                    <a href="index.html" class="mb-15"><img src="<?= $VIEW_PATH . "imgs/main-logo.png" ?>" alt="logo" /></a>
                                    <p class="font-lg text-heading"><?=$setting->description?></p>
                                </div>
                                <ul class="contact-infor">
                                    <!-- <li><img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/icon-location.svg" alt="" /><strong>Address: </strong> <span><?=$setting->address?></span></li> -->
                                    <!-- <li><img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/icon-contact.svg" alt="" /><strong>Call Us:</strong><span><?=$setting->tel?>/span></li> -->
                                    <!-- <li><img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/icon-email-2.svg" alt="" /><strong>Email:</strong><span><?=$setting->email?></span></li> -->
                                </ul>
                            </div>
                        </div>
                        <div class="footer-link-widget col">
                            <h4 class="widget-title">Company</h4>
                            <ul class="footer-list mb-sm-5 mb-md-0">
                                <li><a href="<?= $URL_Domain ?>Sponsorships">Sponsorship</a></li>
                             
                            </ul>
                        </div>
                        <div class="footer-link-widget col">
                            <h4 class="widget-title">Account</h4>
                            <ul class="footer-list mb-sm-5 mb-md-0">
                                <li><a href="<?= $URL_Domain ?>Register">Sign In</a></li>
                                <li><a href="<?= $URL_Domain ?>MyWishList">My Wishlist</a></li>
                                <li><a href="<?= $URL_Domain ?>Helps">Help </a></li>
                                <li><a href="<?= $URL_Domain ?>About">About </a></li>
                            </ul>
                        </div>
                        <div class="footer-link-widget col">
                            <h4 class="widget-title">Corporate</h4>
                            <ul class="footer-list mb-sm-5 mb-md-0">
                                <li><a href="<?= $URL_Domain ?>Products">Products</a></li>
                                <li><a href="<?= $URL_Domain ?>Programs">Programs</a></li>
                                <li><a href="<?= $URL_Domain ?>Coupons">Coupons</a></li>
                                <li><a href="<?= $URL_Domain ?>Deal">Deals</a></li>
                                <li><a href="<?= $URL_Domain ?>Jobs">Jobs</a></li>
                                <li><a href="<?= $URL_Domain ?>Networks">Network</a></li>
                                <li><a href="<?= $URL_Domain ?>Prizes">Prizes</a></li>
                                <li><a href="<?= $URL_Domain ?>winners">winners</a></li>
                         
                            </ul>
                        </div>
                        <!-- <div class="footer-link-widget col">
                            <h4 class="widget-title">Popular</h4>
                            <ul class="footer-list mb-sm-5 mb-md-0">
                                <li><a href="#">Milk & Flavoured Milk</a></li>
                                <li><a href="#">Butter and Margarine</a></li>
                                <li><a href="#">Eggs Substitutes</a></li>
                                <li><a href="#">Marmalades</a></li>
                                <li><a href="#">Sour Cream and Dips</a></li>
                                <li><a href="#">Tea & Kombucha</a></li>
                                <li><a href="#">Cheese</a></li>
                            </ul>
                        </div> -->

                        <!-- <div class="footer-link-widget widget-install-app col">
                            <h4 class="widget-title">Install App</h4>
                            <p class="wow fadeIn animated">From App Store or Google Play</p>
                            <div class="download-app">
                                <a href="<?=$setting->app_store?>" class="hover-up mb-sm-2 mb-lg-0"><img class="active" src="<?=$VIEW_PATH?>assets/imgs/theme/app-store.jpg" alt="" /></a>
                                <a href="<?=$setting->google_play?>" class="hover-up mb-sm-2"><img src="<?=$VIEW_PATH?>assets/imgs/theme/google-play.jpg" alt="" /></a>
                            </div>
                            <p class="mb-20">Secured Payment Gateways</p>
                            <img class="wow fadeIn animated" src="<?=$VIEW_PATH?>assets/imgs/theme/payment-method.png" alt="" />
                        </div> -->

                    </div>
                </div>
            </section>
            <div class="container pb-30">
                <div class="row align-items-center">
                    <div class="col-12 mb-30">
                        <div class="footer-bottom"></div>
                    </div>
                    <div class="col-xl-4 col-lg-6 col-md-6">
                        <p class="font-sm mb-0"> <strong class="text-brand">hairizer</strong> <?=$setting->copy_right?></p>
                    </div>
                    <div class="col-xl-4 col-lg-6 text-center d-none d-xl-block">
                        
                        <!-- <div class="hotline d-lg-inline-flex">
                            <img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/phone-call.svg" alt="hotline" />
                            <p><?=$setting->support_tel?><span>24/7 Support Center</span></p>
                        </div> -->
                    </div>
                    <div class="col-xl-4 col-lg-6 col-md-6 text-end d-none d-md-block">
                        <div class="mobile-social-icon">
                            <h6>Follow Us</h6>
                            <a href="<?=$setting->facebook?>"><img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/icon-facebook-white.svg" alt="" /></a>
                            <a href="<?=$setting->twitter?>"><img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/icon-twitter-white.svg" alt="" /></a>
                            <a href="<?=$setting->instagram?>"><img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/icon-instagram-white.svg" alt="" /></a>
                            <a href="<?=$setting->youtube?>"><img src="<?=$VIEW_PATH?>assets/imgs/theme/icons/icon-youtube-white.svg" alt="" /></a>
                        </div>
                        <p class="font-sm"></p>
                    </div>
                </div>
            </div>
        </footer>