<div class="main-header">

    <div class="contain-headers  big-size">
        <div class="first-header ">
            <div class="logo">

                <h4 class="nameSite">
                    <a class="" href="<?= $URL_Domain ?>">
                        <img src="<?= $VIEW_PATH . "imgs/main-logo.png" ?>" alt="hairizer">
                    </a>
                </h4>
            </div>

            <?php
            $id = "pc_header";
            include $VIEW_PATH_INCLUDE . "WebSite/Layout/SearchResult.phtml"; ?>


            <div class="account">
                <span class="me-1 ms-1 me-2"> <a class="text-dark" href="<?= $URL_Domain ?>Helps">Help</a></span>
                <div id="account"></div>

            </div>




        </div>
        <div class="navbars ">
            <ul class="header-ul">
                <li><a class="active" id="show_category" href="<?= $URL_Domain ?>Products">Products</a></li>
                <li><a class="active" href="<?= $URL_Domain ?>Programs">Programs</a></li>
                <li><a class="active" href="<?= $URL_Domain ?>Prizes">Prizes</a></li>
                <li><a class="active" href="<?= $URL_Domain ?>Winners">Winners</a></li>
                <li><a class="active" href="<?= $URL_Domain ?>Coupons">Coupons</a></li>
                <li><a class="active" href="<?= $URL_Domain ?>Deal">Deals</a></li>
                <!-- <li><a class="active" href="<?= $URL_Domain ?>Stores">Businesses</a></li> -->
                <li><a class="active" href="<?= $URL_Domain ?>Networks">Networks</a></li>
                <li><a class="active" href="<?= $URL_Domain ?>Jobs">Jobs</a></li>


            </ul>
        </div>
        <div class=" position-relative">

            <div id="showCat" style="display: none;" class="category-top-header">
                <div id="firstCat"></div>
                <div id="secondCat" class="grids-middel justify-content-center p-1"></div>

            </div>
        </div>
        
    </div>
    <div class="header-bottom"></div>
</div>