<div class="search position-relative">
    <div class="form-group has-search ">
        <i class="bi bi-search form-control-feedback"></i>
        <input data-id="<?= $id ?>" type="text" class="form-control middle-radius search-header-top searchHeader" placeholder="Search">
    </div>

    <div id=<?= $id ?> style="display: none;" class="search-top-header search_result">
        <div  class="row div_header_search_result">

        </div>

    </div>
</div>