<div class="min-size min-header">

    <div class="menu-side ">
        <div class="logo">
            <h4 class="nameSite">
                <a class="" href="<?= $URL_Domain ?>">
                    <img src="<?= $VIEW_PATH . "imgs/main-logo.png" ?>" alt="">
                </a>
            </h4>
        </div>

        <?php
        $id = "small_header";
        include $VIEW_PATH_INCLUDE . "WebSite/Layout/SearchResult.phtml"; ?>

        <div class="user-img menu-right text-dark" id="profNav">
            <i class="bi bi-text-right menu-icon-header "></i>
        </div>


    </div>


</div>