<div class="modal fade bd-example-modal-lg" id="ModalStatus" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Change Status</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="statusFrm">

                    <div class="mb-3">
                        <input type="text" hidden name="idSearch" id="idSearch">
                        <label for="recipient-name" class="col-form-label"> Status:</label>
                        <select class="form-control min-radus " id="status" name="status">
                      
                        </select>
                    </div>


    



                </form>

            </div>

            <div class="modal-footer-glass modal-footer">
                <button  data-id="ModalStatus" id="btnStatus" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>