<div class="containerlogin">
    <div class="d-flex justify-content-center mt-5">

        <div class="row m-2 p-1 back-login-div widths ">
            <h1 class="login-text-header mb-4 mt-4">Activate Account</h1>


            <div id="action" class="mb-3">
                <div class=" width-btn  radus">
                    <div class="alert alert-<?=$data['status']?> p-4 m-1">
                        <strong><?=$data['txt']?></strong>
                    </div>
                </div>
            </div>

            <div class="mt-2 mb-2">
                <p class="txt">Go To <a href="<?= $URL_Domain ?>">Home</a></p>
            </div>

        </div>
    </div>
</div>