<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><?=$titleSearch?></label>
    <div class="d-flex form-control">
        <input autocomplete="off" type="text" style="border: none;" class="input-white" id="<?=$idInput?>">
        <div style="display: none;" class="spinner-border text-dark" role="status">
            <span class="sr-only"></span>
        </div>
    </div>
    <div style="max-height: 300px;overflow-y: scroll;overflow-x: hidden;"  id="<?=$idResult?>"></div>

</div>