<link rel="stylesheet" href="<?= $VIEW_PATH ?>css/UserDashboard/Layout/SideMenu.css">

<div id="sideBar" class="iq-sidebar   sidebar-default mt-3">

    <div class="data-scrollbar" data-scroll="1" data-scrollbar="true" tabindex="-1">
        <div class="scroll-content">
            <nav class="iq-sidebar-menu">
                <ul id="iq-sidebar-toggle" class="iq-menu">
                    <li class=" pl">
                        <a href="<?= $URL_Domain ?>UserDashboard" class="svg-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" width="20" height="20">
                                <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path>
                            </svg>
                            <span class="ml-3"> Dashboard</span>
                        </a>
                    </li>

                    <li class=" pl">
                        <a href="<?= $URL_Domain ?>Profile" class="svg-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                            </svg>
                            <span class="ml-3"> Profile</span>
                        </a>
                    </li>

                    <li class=" pl">
                        <a id="DealsP" data-id="Deals" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z" />
                                <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z" />
                                <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z" />
                                <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z" />
                            </svg>
                            <span class="ml-3">Deals&Coupon</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="Deals" data-parentid="DealsP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>UserShopDealsList" class="sub-menu" data-parent="DealsP">
                                    <i class="las la-minus"></i><span>My Deals </span>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?= $URL_Domain ?>UserShopCouponList" class="sub-menu" data-parent="DealsP">
                                    <i class="las la-minus"></i><span>My Coupon </span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="banners" data-id="banner" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-badge-ad" viewBox="0 0 16 16">
                                <path d="m3.7 11 .47-1.542h2.004L6.644 11h1.261L5.901 5.001H4.513L2.5 11h1.2zm1.503-4.852.734 2.426H4.416l.734-2.426h.053zm4.759.128c-1.059 0-1.753.765-1.753 2.043v.695c0 1.279.685 2.043 1.74 2.043.677 0 1.222-.33 1.367-.804h.057V11h1.138V4.685h-1.16v2.36h-.053c-.18-.475-.68-.77-1.336-.77zm.387.923c.58 0 1.002.44 1.002 1.138v.602c0 .76-.396 1.2-.984 1.2-.598 0-.972-.449-.972-1.248v-.453c0-.795.37-1.24.954-1.24z" />
                                <path d="M14 3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h12zM2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2z" />
                            </svg>
                            <span class="ml-3">Advertise with us</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="banner" data-parentid="banners" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>UserBannerOrder" class="sub-menu" data-parent="banners">
                                    <i class="las la-minus"></i><span>Banner Order</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?= $URL_Domain ?>MySponsorShipOrder" class="sub-menu" data-parent="banners">
                                    <i class="las la-minus"></i><span>SponsorShip</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="payments" data-id="payment" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-exchange" viewBox="0 0 16 16">
                                <path d="M0 5a5.002 5.002 0 0 0 4.027 4.905 6.46 6.46 0 0 1 .544-2.073C3.695 7.536 3.132 6.864 3 5.91h-.5v-.426h.466V5.05c0-.046 0-.093.004-.135H2.5v-.427h.511C3.236 3.24 4.213 2.5 5.681 2.5c.316 0 .59.031.819.085v.733a3.46 3.46 0 0 0-.815-.082c-.919 0-1.538.466-1.734 1.252h1.917v.427h-1.98c-.003.046-.003.097-.003.147v.422h1.983v.427H3.93c.118.602.468 1.03 1.005 1.229a6.5 6.5 0 0 1 4.97-3.113A5.002 5.002 0 0 0 0 5zm16 5.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0zm-7.75 1.322c.069.835.746 1.485 1.964 1.562V14h.54v-.62c1.259-.086 1.996-.74 1.996-1.69 0-.865-.563-1.31-1.57-1.54l-.426-.1V8.374c.54.06.884.347.966.745h.948c-.07-.804-.779-1.433-1.914-1.502V7h-.54v.629c-1.076.103-1.808.732-1.808 1.622 0 .787.544 1.288 1.45 1.493l.358.085v1.78c-.554-.08-.92-.376-1.003-.787H8.25zm1.96-1.895c-.532-.12-.82-.364-.82-.732 0-.41.311-.719.824-.809v1.54h-.005zm.622 1.044c.645.145.943.38.943.796 0 .474-.37.8-1.02.86v-1.674l.077.018z" />
                            </svg>
                            <span class="ml-3">Payments</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="payment" data-parentid="payments" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>UserPaymentList" class="sub-menu" data-parent="payments">
                                    <i class="las la-minus"></i><span>Payment List</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="wishes" data-id="wish" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
                                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z" />
                            </svg>
                            <span class="ml-3">Wish List</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="wish" data-parentid="wishes" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>MyWishList" class="sub-menu" data-parent="wishes">
                                    <i class="las la-minus"></i><span>List</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    

                    <li class=" pl">
                        <a id="follows" data-id="follow" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <i class="fas fa-wifi"></i>
                            <span class="ml-3">Connection</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="follow" data-parentid="follows" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>MyFollower" class="sub-menu" data-parent="follows">
                                    <i class="las la-minus"></i><span>Follower</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>MyFollowing" class="sub-menu" data-parent="follows">
                                    <i class="las la-minus"></i><span>Following</span>
                                </a>
                            </li>
                        </ul>
                    </li>


                    <li class=" pl">
                        <a id="supports" data-id="support" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                        <i class="fas fa-headset"></i>
                            <span class="ml-3">Support</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="support" data-parentid="supports" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>SupportList" class="sub-menu" data-parent="supports">
                                    <i class="las la-minus"></i><span>Support List</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    

                    <li class=" pl">
                        <a id="messages" data-id="message" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chat-right-dots-fill" viewBox="0 0 16 16">
                                <path d="M16 2a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h9.586a1 1 0 0 1 .707.293l2.853 2.853a.5.5 0 0 0 .854-.353V2zM5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
                            </svg>
                            <span class="ml-3">Message</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="message" data-parentid="messages" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>MyInbox" class="sub-menu" data-parent="messages">
                                    <i class="las la-minus"></i><span>Inbox</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>MySend" class="sub-menu" data-parent="messages">
                                    <i class="las la-minus"></i><span>Send</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    
                </ul>
            </nav>

            <div class="pt-5 pb-2"></div>
        </div>
        <div class="scrollbar-track scrollbar-track-x" style="display: none;">
            <div class="scrollbar-thumb scrollbar-thumb-x" style="width: 274px; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
        <div class="scrollbar-track scrollbar-track-y" style="display: block;">
            <div class="scrollbar-thumb scrollbar-thumb-y" style="height: 60.6143px; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
    </div>
</div>