<div class="mb-3">
                        <label for="recipient-name" class="col-form-label">First Name:</label>
                        <input type="text" class="input-white min-radus " name="fname" id="fname<?=$edit?>">
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Last Name:</label>
                        <input type="text" class="input-white min-radus " name="lname" id="lname<?=$edit?>">
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Email:</label>
                        <input type="text" class="input-white min-radus " name="email" id="email<?=$edit?>">
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Password:</label>
                        <input type="text" class="input-white min-radus " name="password" id="password<?=$edit?>">
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Verify:</label>
                        <select name="verify" class="form-control" id="verify<?=$edit?>">
                            <option value=""></option>
                            <option value="1">Yes</option>
                            <option value="0">No</option>
                        </select>
                    </div>