<div class="modal fade bd-example-modal-lg" id="ModalView" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Message</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div id="result_msg" class="mb-5"></div>
                <div class="mt-5">
                    <button class="btn btn-sm btn-prim" style="display: none;" id="BtnLoad">Lode More</button>

                </div>
                <form id="addMsg">
                    <input type="text" hidden name="to_user" id="to_user">
                    <input type="text" hidden name="message_id" id="message_id">
                    <div class="row">
                        <div class="col-md-10">
                            <textarea class="form-control" rows="1" name="txt" id="txt"></textarea>
                        </div>
                        <div class="col-md-2">
                            <button data-id="ModalView" id="btnAddMessage" type="button" class="btn  btn-glass">Send</button>

                        </div>
                    </div>

                </form>
            </div>

            <div class="modal-footer-glass modal-footer">

            </div>
        </div>
    </div>
</div>