<div class="modal fade bd-example-modal-lg" id="ModalEditImage" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Edit Image</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="d-flex  justify-content-center">
                    <div class="col-md-4 text-center rounded  mb-2" id="imagep"></div>
                    <input type="text" hidden  id="idSearchImage">
                </div>
                <div class="d-flex  justify-content-center" >
                    <button id="btndeleteimageevent" class="btn btn-sm btn-danger btn-remove m-1 b-radus"><i class="bi bi-trash"></i></button>

                </div>
                <div class="mb-3">
                    <input type="file" name="file_image_edit" id="file_image_edit" class="fileinputs">

                </div>
            </div>
            <div class="modal-footer-glass modal-footer">
                <button data-id="ModalEditImage" id="BtnEditImage" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>