<div class="mb-3 " id="more_cat<?=$edit?>"></div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Title:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="title<?=$edit?>" name="title">
</div>


<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Value:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="amount<?=$edit?>" name="amount">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Search Product:</label>
    <select style="width: 100%" class="input-white min-radus  productsearch select-css" multiple name="product_id" id="product_id<?=$edit?>">

    </select>

</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> type:</label>
    <select class="form-control min-radus"  name="type" id="type<?=$edit?>"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Expire Date:</label>
    <input type="date" autocomplete="off" class="form-control min-radus " name="expire" id="expire<?=$edit?>">
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Link:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " name="link" id="link<?=$edit?>">
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Description:</label>
    <textarea rows="5" class="form-control min-radus "  name="description" id="description<?=$edit?>"></textarea>
</div>