<div class="modal fade bd-example-modal-lg" id="ModalEdit" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Team</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="editForm">
                    <?php
                    $edit = "_e";
                    include $VIEW_PATH_ADMIN_INCLUDE . "Team/modal/TeamItem.phtml";

                    ?>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Display Name:</label>
                        <input name="display_name" id="display_name" type="text" autocomplete="off" class="form-control min-radus ">
                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-id="ModalEdit" id="btnModalEdit" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>