<div class="modal fade bd-example-modal-lg" id="ModalShowNotification" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Your Notification</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                
                    <div class="mb-3" id="show_text">
                 
                    </div>

              

         
            </div>

            <div class="modal-footer-glass modal-footer">

            </div>
        </div>
    </div>
</div>