<?php

   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Remove.phtml";
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/AddNewBanner.phtml";
   include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/EditImage.phtml";
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Category.phtml";

?>
<div class="covers">
<input type="text" hidden id="creator_types" value="<?=$data['creator_type']?>">
    <div class=" m-top mb-3">
        <div class="row">
       

      
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>TransActionId</th>
                <th>Currency</th>
                <th>status</th>
                <th>Amount</th>
                <th>Date</th>
 
            </tr>
        </thead>

    </table>
</div>