<?php

include_once $VIEW_PATH_INCLUDE."UserDashboard/Notification/modal/ShowNotification.phtml";


?>
<div class="covers">

    <div class="covers mb-3">
        <div class="row">
      
        <input type="text" id="notes_types" hidden value="<?=$data['notes_type']?>">
        
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">ID:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">text:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="texts">
                </div>
            </div>

            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Read:</label>
                    <select class="form-control" name="" id="is_reads">
                        <option value=""></option>
                        <option value="1">Yes</option>
                        <option value="0">No</option>
                    </select>
                </div>
            </div>

            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Type</th>
                <th>Text</th>
                <!-- <th>Disabled</th> -->
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>