<div class="modal fade bd-example-modal-lg" id="ModalAdd" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Discount</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="addFrm">
                    <?php
                    $edit = "";
                    include $VIEW_PATH_INCLUDE . "Admin/Tables/Discount/Items.phtml";
                    ?>


                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-editid="" data-id="ModalAdd" id="btnAdd" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>