<div class="modal fade bd-example-modal-lg" id="ModalAddCopy" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Discount</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="addFrmCopy">

                    <input type="text" name="idSearch" id="idSearchCopy" hidden>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> Number Of Copy:</label>
                        <input type="number" class="form-control" name="number_copy" id="number_copy">
                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-id="ModalAddCopy" id="btnAddCopy" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>