<?php

?>
<div class="covers">
<div class="mb-4">
        <span class="sm-font">
            <a href="<?= $URL_Domain ?><?= $data['listHref'] ?>"><?= $data['list'] ?></a>
        </span>
        <span class="sm-font"><i class="bi bi-chevron-right"></i></span>
        <span class="sm-font"><?=$data['title_page']?></span>
    </div>

    <div class="covers m-top mb-3">
        <div class="row">
            <div class="col-md-12 mb-2">
           
            </div>

            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">ID:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">status:</label>
                    <select name="status" id="status" class="form-control min-radus "></select>
                </div>
            </div>
       
            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Job Title</th>
                <th>Post Date</th>
                <th>Status</th>
    
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>