
<div class="covers">

    <div class="covers mb-3">
        <div class="row">

            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">User Name:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="display_name">
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Title:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="titlese">
                </div>
            </div>

            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>User Name</th>
                <th>text</th>
                <th>Send Date</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>