<?php
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/Category.phtml";
?>
<div class="m-top covers text-dark">
    <div class="mb-4">
        <span class="sm-font">
            <a href="<?= $URL_Domain ?><?= $data['listHref'] ?>"><?= $data['list'] ?></a>
        </span>
        <span class="sm-font"><i class="bi bi-chevron-right"></i></span>
        <span class="sm-font"><?=$data['pageTitle']?></span>
    </div>

    <form id="frmNew">
        <?php
        include_once $VIEW_PATH_INCLUDE . "BusinessDashboard/Product/Items.phtml";
        ?>
        <div class="mb-3">
            <input accept=".png, .jpg, .jpeg" type="file" name="product_image" id="main_image" class="fileInputs">


        </div>
    </form>
    <div class="row">
        <div class="col-md-12 mt-5 mb-5 text-center">
            <button id="btnSave" type="button" class="btn  btn-glass">Save</button>

        </div>
    </div>
</div>