<div class="mb-3 row">
    <label for="recipient-name" class="col-form-label">Select a city or select an online option for all cities</label>

    <div class="col-md-3">
        <label class="chboxs ">Online
            <input type="checkbox" id="online" name="online" value="1">
            <span class="checkmark"></span>
        </label>
    </div>
    <div class="col-md-3">

        <select style="width: 100%;" id="country_id" name="country_id" class="form-control select2">

        </select>
    </div>
    <div class="col-md-3">
        <select style="width: 100%;" name="province_id" id="province_id" class="form-control select2"></select>
    </div>
    <div class="col-md-3">
        <select style="width: 100%;" name="city_id" id="city_id" class="form-control select2"></select>
    </div>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Title:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="title" name="title">
</div>

<div class="mb-3">
    <!-- <label for="recipient-name" class="col-form-label">Category:</label> -->
    <!-- <div data-dismiss="modal" type="text" class="form-control p-3 min-radus point" id="category_id"></div> -->

</div>
<div class="mb-3 " id="more_cat"></div>

<div class="mb-3">
    <button type="button" id="add_more_cat" data-id="more_cat" class="btn btn-glass">Add More</button>
    <button type="button" id="reset_cat" data-id="more_cat" class="btn btn-danger m-1">Remove All</button>

</div>

<div class="mb-3 row" id="more_link">
    <div class="col-md-4">
        <label for="recipient-name" class="col-form-label">Link type:</label>
        <select id="ltype1" class="form-control min-radus select-css ">
            <option value=""></option>
            <option value="buy">Buy</option>
            <option value="video">Video</option>

        </select>
    </div>
    <div class="col-md-4">
        <label for="recipient-name" class="col-form-label">Link Title:</label>
        <input id="ltitle1" type="text" autocomplete="off" class="form-control min-radus ">
    </div>
    <div class="col-md-4">
        <label for="recipient-name" class="col-form-label">Link Address:</label>
        <input id="ltag1" type="text" autocomplete="off" class="form-control min-radus ">
    </div>


</div>

<div class="mb-3">
    <button type="button" id="add_more_links" data-id="more_link" class="btn btn-glass">Add More</button>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Price:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="price" name="price">
</div>


<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Hair Type:</label>
    <select class="form-control min-radus select2" multiple  name="hair_type" id="hair_type<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Skin type:</label>
    <select class="form-control min-radus select2" multiple  name="skin_type" id="skin_type<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Liquid Volume:</label>
    <select class="form-control min-radus select2" multiple  name="liquid_volume" id="liquid_volume<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Item Dimensions :</label>
    <select class="form-control min-radus select2" multiple  name="item_dimensions" id="item_dimensions<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Product Benefits:</label>
    <select class="form-control min-radus select2" multiple  name="benefits" id="benefits<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Special Ingredients:</label>
    <select class="form-control min-radus select2" multiple  name="special_ingredients" id="special_ingredients<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Item Form:</label>
    <select class="form-control min-radus select2" multiple  name="item_form" id="item_form<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Active Ingredients:</label>
    <select class="form-control min-radus select2" multiple  name="active_ingredients" id="active_ingredients<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Age Range:</label>
    <select class="form-control min-radus select2" multiple  name="age_range" id="age_range<?=$edit?>"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Description:</label>
    <textarea rows="5" class="form-control min-radus " id="description" name="description"></textarea>
</div>

