<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Title:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="title<?=$edit?>" name="title">
</div>

<div class="mb-3 " id="more_cat<?=$edit?>"></div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> type:</label>
    <select class="form-control min-radus select2" multiple  name="type" id="type<?=$edit?>"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Gender:</label>
    <select class="form-control min-radus select2" multiple  name="gender"  id="gender<?=$edit?>"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Salary:</label>
    <select class="form-control min-radus select2" multiple  name="salary" id="salary<?=$edit?>"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Benefit:</label>
    <select class="form-control min-radus select2" multiple  name="benefit" id="benefit<?=$edit?>"></select>
</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Level:</label>
    <select class="form-control min-radus select2" multiple  name="level" id="level<?=$edit?>"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Exprience:</label>
    <select class="form-control min-radus select2" multiple  name="exprience" id="exprience<?=$edit?>"></select>
</div>


<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Search Skill:</label>
    <select style="width: 100%" class="input-white min-radus  skillSearch select-css" multiple name="skill" id="skill<?=$edit?>">

    </select>

</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Description:</label>
    <textarea rows="5" class="form-control min-radus "  name="description" id="description<?=$edit?>"></textarea>
</div>