<?php

   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Remove.phtml";
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/AddNewBanner.phtml";
   include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/EditImage.phtml";
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Category.phtml";

?>
<div class="covers">
<input type="text" hidden id="creator_types" value="<?=$data['creator_type']?>">
    <div class="covers m-top mb-3">
        <div class="row">
        

      
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Company</th>
                <th>Category</th>
                <th>Contact</th>
                <th>Mobile</th>
                <th>Fax</th>
                <th>Email</th>
                <th>Address</th>
                <th>Payment</th>
                <th>Options</th>
                <!-- <th>Action</th> -->
            </tr>
        </thead>

    </table>
</div>