<?php
 include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/RemoveAdmin.phtml";
 include_once ($VIEW_PATH_ADMIN_INCLUDE ."Team/modal/AddTeam.phtml");
 include_once ($VIEW_PATH_ADMIN_INCLUDE ."Team/modal/EditTeam.phtml");
 include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/EditImage.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/ImageGallery.phtml";
// include_once $VIEW_PATH_ADMIN_INCLUDE . "Common/modal/SendToTop.phtml";
?>
<div class="covers m-top">

    <div class="covers mb-3">
        <form id="searchfrm">
            <div class="row">
            <div class="col-md-12 mb-2">
                <small id="addNewBtn" class="btn btn-prim btn-lg ">
                    <i class="bi bi-plus-lg mr-2"></i> Add Team
                </small>
            </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">ID:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Email:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="emails">
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">First Name:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="fnames">
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Last Name:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="lnames">
                    </div>
                </div>

                
        

                <div class="col-md-12 mb-2 text-center">
                    <button type="button" id="searchbtn" class="btn btn-prim btn-lg">
                        <i class="bi bi-search mr-2"></i> Search
                    </button>
                    <button id="reset" type="button" class="btn  btn-lg">
                        Reset
                    </button>
                </div>
            </div>
        </form>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Activities</th>
                <th>Public</th>
                <th>Disabled</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>