<?php

   include_once $VIEW_PATH_INCLUDE."Message/modal/View.phtml";

?>
<div class="covers">

    <div class="covers m-top mb-3">
        <div class="row">
            <div class="col-md-12 mb-2">
             
            </div>

            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">ID:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                </div>
            </div>
            <!-- <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Title:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="titlese">
                </div>
            </div> -->

            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>From</th>
                <th>Txt</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>