<div class="modal fade bd-example-modal-lg" id="ModalAccept" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Accept</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="acceptFrm">

                <p class="h5">Are you sure?</p>
                <input type="text" hidden name="idSearch" id="idSearch">
                <input type="text" hidden name="status" id="status" value="1">


    
                </form>

                <div class="m-4 row" id="result_top"></div>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button  data-id="ModalAccept" id="btnAccept" type="button" class="btn  btn-success">Accept</button>

            </div>
        </div>
    </div>
</div>