<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Disabled Status :</label>
    <label class="radiobox">Don't Disabled
        <input type="radio" value="0"  name="trash" id="trash">
        <span class="chmr"></span>
    </label>
    <label class="radiobox">Disabled
        <input type="radio" value="1" name="trash" id="trash2">
        <span class="chmr"></span>
    </label>

</div>