<?php

include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/RemoveAdmin.phtml";
include_once $VIEW_PATH_INCLUDE."Admin/Program/modal/AddNew.phtml";
include_once $VIEW_PATH_INCLUDE."Admin/Program/modal/EditInfo.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/EditImage.phtml";
include_once $VIEW_PATH_INCLUDE."Admin/Program/modal/ViewData.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/ImageGallery.phtml";


?>
<div class="covers m-top">

<div class="covers mt-1 mb-3">
    <form id="searchfrm">
        <div class="row">
        <div class="col-md-12 mb-2">
            <a href="<?=$DURL_Domain?>AddAdSetting" class="btn btn-prim btn-lg ">
                <i class="bi bi-plus-lg mr-2"></i> Add Option
            </a>
        </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">ID:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Title:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="titlese">
                </div>
            </div>


            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Type:</label>
                    <select class="form-control min-radus " id="typeS"></select>
                </div>
            </div>


          


            <div class="col-md-12 mb-2 text-center">
                <button type="button" id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
                <!-- <button id="reset" type="button" class="btn  btn-lg">
                    Reset
                </button> -->
            </div>
        </div>
    </form>
</div>
<table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
    <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Type</th>
            <th>Key Word</th>
            <th>Price</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>

</table>
</div>