<div class="d-flex justify-content-center">
<div class="  m-top" style="width: 50%;">

    <div class="row mt-5 border-left border-right border-bottom">
        <div class="col-md-12 row border-bottom align-items-center p-2">
            <div class="col-md-4 border-right p-2">
                <?php if ($data['url'] != '') { ?>
                    <img src="https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl=<?= $data['url'] ?>&choe=UTF-8" title="Link to Google.com" />
                <?php } ?>
            </div>
            <div class="col-md-8 p-2 text-center">
                <h4><?= $data['title'] ?></h4>
            </div>
        </div>
        <div class="col-md-12 text-center text-info border-bottom p-2">
            <h5><strong><?=$data['code']?></strong></h5>
        </div>
        <br>
        
        <div class="col-md-12  p-2 border-bottom">
            <span> <?=$data['description']?></span>
        </div>
        <br>
        <div class="col-md-12 text-center p-2">
            <p>Expire in <?=$data['expire']?></p>
        </div>

        <div class="col-md-12  p-2">
            <?=$SiteName?>
        </div>
    </div>
</div>
</div>
