<?php
$btn_title="Program";
$admin=true;
include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/RemoveAdmin.phtml";
include_once $VIEW_PATH_INCLUDE."Admin/Program/modal/AddNew.phtml";
include_once $VIEW_PATH_INCLUDE."Admin/Program/modal/EditInfo.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/EditImage.phtml";
include_once $VIEW_PATH_INCLUDE."Admin/Program/modal/ViewData.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/ImageGallery.phtml";

include_once $VIEW_PATH_ADMIN_INCLUDE . "Tables/ViewProgram.phtml";
?>