<div class="modal fade bd-example-modal-lg" id="ModalView" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="row text-start text-dark">
               
                    <div class="col-md-12 text-center mb-1 h5" id="title">

                    </div>

                    <div class="col-md-12"><strong>Studio:</strong></div>
                    <div class="col-md-12 p-1 mb-1" id="studio">

                    </div>

                    <div class="col-md-12"><strong>Date:</strong></div>
                    <div class="col-md-12 p-1 mb-1" id="date">

                    </div>
  
                    <div class="col-md-12"><strong>Description:</strong></div>

                    <div class="col-md-12 p-1 mb-1">
                        <p id="description"></p>
                    </div>
                </div>

            </div>
            <div class="modal-footer-glass modal-footer">
            </div>
        </div>
    </div>
</div>