<?php

?>
<div class="covers">

    <div class="covers m-top mb-3">
        <div class="row">
 

          
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Type:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="type">
                </div>
            </div>

            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Type</th>
                <th>Item id</th>
                <th>Item Name</th>
                <th>Numbers</th>
                <th>Report</th>
                <!-- <th>Action</th> -->
            </tr>
        </thead>

    </table>
</div>