<?php
   include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Employee/modal/Accepted.phtml";
  
?>
<div class="covers ">

    <div class="covers m-top mb-3">
        <div class="row">
            <div class="col-md-12 mb-2">
                <!-- <small id="addNewBtn" class="btn btn-prim btn-lg ">
                    <i class="bi bi-plus-lg mr-2"></i> Add Business
                </small> -->
            </div>

            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">ID:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Name:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="titlese">
                </div>
            </div>

            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <!-- <th>Date start</th>
                <th>Date End</th> -->
                <!-- <th>Disabled</th> -->
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>