<?php

$datas = $data['datas'];
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/Category.phtml";
include_once $VIEW_PATH_INCLUDE . "WebSite/modal/ViewDataModify.phtml";
?>

<input type="text" name="idSearch" id="idSearch" value="<?=$data['idSearch']?>" hidden>
<div class="contains-item-page ">
    <div class="row">
        <div class="col-md-12 text-center mb-2">
            <h1><strong>Contact With Us</strong></h1>
        </div>


    </div>


    <div class="row mt-5 ms-2 me-2">


        <form id="frmContact">
            <div class="row">
        <div class="col-md-6">
            <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span>Department (Legal, Programs, Advertise with us, Technical)  :</label>
            <div class="input-group mb-3 ">
                <span class="input-group-text middle-radius-top-left middle-radius-bottom-left">
                    <i class="bi bi-building"></i></span>
                <input type="text" name="company" id="company"  class="form-control middle-radius-top-right middle-radius-bottom-right">
            </div>
        </div>

        <div class="col-md-6">
        <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span>Name :</label>

            <div class="input-group mb-3 ">
                <span class="input-group-text middle-radius-top-left middle-radius-bottom-left">
                    <i class="bi bi-file-person"></i>
                </span>
                <input type="text" name="name" id="name" class="form-control middle-radius-top-right middle-radius-bottom-right">
            </div>
        </div>
        <div class="col-md-6">
        <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span>Phone :</label>

            <div class="input-group mb-3 ">
                <span class="input-group-text middle-radius-top-left middle-radius-bottom-left">
                    <i class="bi bi-telephone"></i>
                </span>
                <input type="text" name="phone" id="phone" class="form-control middle-radius-top-right middle-radius-bottom-right">
            </div>
        </div>


        <div class="col-md-6">
        <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span>Email :</label>

            <div class="input-group mb-3 ">
                <span class="input-group-text middle-radius-top-left middle-radius-bottom-left">
                    <i class="fas fa-envelope"></i>
                </span>
                <input type="text" name="email" id="email" class="form-control middle-radius-top-right middle-radius-bottom-right">
            </div>
        </div>
        <div class="col-md-12">
        <label for="recipient-name" class="col-form-label">Description :</label>

            <div class="input-group mb-3 ">
             
                <textarea name="description" id="description" class="form-control middle-radius-top-right middle-radius-bottom-right"></textarea>
            </div>
        </div>
        </div>
        </form>
        
        <?php include $VIEW_PATH_INCLUDE . "Captcha.html";?>
        <div class="mb-5 mt-3 col-md-12 text-center">
            
            <button class="btn btn-success" id="SaveData">Send</button>
        </div>
    </div>



</div>