<div class="main mt-2">

    <?php include_once $VIEW_PATH_INCLUDE . "WebSite/BigBanner.phtml"; ?>


    <?php if (isset($data['display_name_slug'])) {
        $display_name_slug = $data['display_name_slug'];
    } else $display_name_slug = "" ?>
    <input type="text" hidden id="display_name_slug" value="<?= $display_name_slug ?>">

    <div class="container mb-30">
        <div class="row flex-row-reverse">
            <div class="col-lg-5-5">
                <div class="shop-product-fillter">
                    <div class="totall-product">
                        <p> <strong class="text-brand"><?= number_format($data['total']) ?></strong> items</p>
                    </div>
                    <div class="sort-by-product-area">

                       
                    </div>
                </div>
                <div class="row product-grid">
                    <input type="text" hidden value="<?= $data['idNotIn'] ?>" id="idNotIn">
                    <?php
                    foreach ($data['data'] as $d) { ?>
                        <div class=" col-md-3 col-12 col-sm-6  mb-30">
                            <?php switch ($data['type_shows']) {


                                case "prize": {
                                        include $VIEW_PATH_INCLUDE . "WebSite/Cards/Prize.phtml";
                                        break;
                                    }
                                case "coupon": {
                                        include $VIEW_PATH_INCLUDE . "WebSite/Cards/Coupon.phtml";
                                        break;
                                    }
                                case "deals": {
                                        include $VIEW_PATH_INCLUDE . "WebSite/Cards/Deals.phtml";
                                        break;
                                    }


                                case "winner": {
                                        include $VIEW_PATH_INCLUDE . "WebSite/Cards/Winner.phtml";
                                        break;
                                    }

                                case "user": {
                                        include $VIEW_PATH_INCLUDE . "WebSite/Cards/User.phtml";
                                        break;
                                    }
                                case "program": {
                                        include $VIEW_PATH_INCLUDE . "WebSite/Cards/Program.phtml";
                                        break;
                                    }
                                case "job": {
                                        include $VIEW_PATH_INCLUDE . "WebSite/Cards/Job.phtml";
                                        break;
                                    }
                            }
                            ?>
                        </div>
                    <?php } ?>



                </div>
                <!--product grid-->
                <div class="pagination-area mt-20 mb-20">
                    <div class="row">
                        <?php $indexBanner = "1";
                        include $VIEW_PATH_INCLUDE . "WebSite/BigBanner.phtml"; ?>
                    </div>
                    <div class="col-md-12 text-center mt-3">
                        <?php if ($data['haveMore']) { ?>
                            <button class="btn btn-sm btn-prim" id="BtnnLoad">Lode More</button>
                        <?php } ?>

                    </div>
                </div>

            </div>
         
        </div>
    </div>

</div>