<?php
$datas = $data['data'][0];

$BuyTag = false;
$socialTag = false;

$links = explode(",", $datas->product_tag);
foreach ($links as $li) {
    $l = explode("::", $li);

    if ($l[3] === "buy") {
        $BuyTag = true;
    }
}

$phone = false;
$email = false;
$address = false;

$report = $data['report'];
$table = "product";
$item_id = $datas->id;
$gallery = [];
if ($datas->product_gallery !== null && $datas->product_gallery !== '') {
    $gallery = explode(",", $datas->product_gallery);
}



include_once $VIEW_PATH_INCLUDE . "WebSite/modal/AddReport.phtml";
include_once $VIEW_PATH_INCLUDE . "WebSite/modal/AddRate.phtml";
include_once $VIEW_PATH_INCLUDE . "WebSite/modal/AddReview.phtml";
include_once $VIEW_PATH_INCLUDE . "WebSite/modal/AddReplyComment.phtml";
include_once $VIEW_PATH_INCLUDE . "WebSite/modal/Login.phtml";
include_once $VIEW_PATH_INCLUDE . "WebSite/modal/Clime.phtml";

$imgUrl = $VIEW_PATH . "assets/imgs/shop/product-16-1.jpg";
if ($datas->file_url !== "" && $datas->file_url !== null) {
    $imgUrl = $URL_PATH . $datas->file_url . '/thumb/' . $datas->file_name;
}
$imgs = [];
array_push($imgs, $imgUrl);
foreach ($gallery as $g) {
    $attach = explode("::", $g);
    $file_url = $attach[1];
    $file_name = $attach[2];
    array_push($imgs, $URL_PATH . $file_url . "/thumb/" . $file_name);
}

$price = $datas->price;
if ($price == null || $price == '')
    $price = 0;

$mainPrice = 0;
if ($datas->amount !== null) {
    if ($datas->coupon_type == "Numerical") {
        $mainPrice = $price - $datas->amount;
    }

    if ($datas->coupon_type == "Percent") {
        $mainPrice = $price - (($price * $datas->amount) / 100);
    }
}

$logo = $URL_Domain . $VIEW_PATH_INCLUDE . "imgs/logo.png";
if ($datas->logo_url != '' && $datas->logo_url != null) {
    $logo = $URL_PATH . $datas->logo_url . "/small/" . $datas->logo_name;
}

?>
<input type="text" hidden value="<?= $data['logged'] ?>" id="logged">
<input type="text" hidden value="<?= $data['user_online_id'] ?>" id="user_online_id">
<input type="text" hidden id="type_creator" value="<?= $data['type_creator'] ?>">
<input type="text" hidden id="product_id" value="<?= $datas->id ?>">
<input type="text" hidden id="idSearch" value="<?= $datas->id ?>">
<input type="text" hidden id="tableType" value="product">
<input type="text" hidden id="email_user" value="<?= $data['email_online'] ?>">
<input type="text" hidden id="display_name_user" value="<?= $data['display_name_online'] ?>">
<input type="text" hidden id="title_item" value="product: <?= $datas->title ?>">

<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="<?= $URL_Domain ?>" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> <a href="<?= $URL_Domain ?>Products">Products</a> <span></span><?= $datas->title ?>
            </div>
        </div>
    </div>
    <div class="container mb-30">
        <div class="row">
            <div class="col-xl-10 col-lg-12 m-auto">
                <div class="product-detail accordion-detail">
                    <div class="row mb-10 mt-30">
                        <div class="col-md-4 col-sm-12 col-xs-12 mb-md-0 mb-sm-1">
                            <div class="detail-gallery">
                                <span class="zoom-icon">
                                    <!-- <i class="fi-rs-search"></i> -->
                                </span>
                                <!-- MAIN SLIDES -->
                                <div class="product-image-slider">
                                    <?php foreach ($imgs as $im) { ?>
                                        <figure class="border-radius-10">
                                            <img src="<?= $im ?>" alt="<?= $datas->title ?>" />
                                        </figure>
                                    <?php } ?>


                                </div>
                                <!-- THUMBNAILS -->
                                <div class="slider-nav-thumbnails">
                                    <?php foreach ($imgs as $im) { ?>
                                        <div><img src="<?= $im ?>" alt="<?= $datas->title ?>" /></div>

                                    <?php } ?>

                                </div>
                            </div>
                            <!-- End Gallery -->
                        </div>
                        <div class="col-md-8 col-sm-12 col-xs-12">
                            <div class="detail-info pr-30 pl-30">
                                <!-- <span class="stock-status out-stock"> Sale Off </span> -->
                                <h2 class="title-detail"><?= $datas->title ?></h2>
                                <div class="product-detail-rating">
                                    <div class="product-rate-cover text-end">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: <?= intval($datas->Rating) * 20 ?>%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (<?= number_format($datas->total_rate) ?> Ratings)</span>
                                    </div>
                                </div>
                                <div class="clearfix product-price-cover">
                                    <div class="product-price primary-color float-left">
                                        <?php if ($mainPrice != 0) { ?>
                                            <span class="current-price text-brand">$<?= number_format($mainPrice) ?></span>
                                            <span>
                                                <span class="save-price font-md color3 ml-15"> <?= $datas->coupon_type == "Numerical" ? "$" : "" ?>
                                                    <?= ($datas->amount) ?>
                                                    <?= $datas->coupon_type == "Percent" ? " %" : "" ?> Off</span>
                                                <span class="old-price font-md ml-15">$<?= number_format($price) ?></span>
                                            </span>
                                        <?php } else {  ?>
                                            <span class="current-price text-brand">$<?= number_format(floatval($datas->price)) ?></span>
                                        <?php } ?>
                                    </div>
                                </div>
                                <div class="short-desc mb-30">
                                    <p class="font-lg"><?= $datas->description ?></p>
                                </div>

                                <div class="detail-extralink mb-50">

                                    <div class="product-extra-link2">
                                        <?php
                                        $title = $datas->title;
                                        $id = $datas->id;
                                        $type = "product";
                                        $url =  $URL_Domain . "ProductDetail/" . $datas->title_slug;
                                        include $VIEW_PATH_INCLUDE . "WebSite/Share.phtml"; ?>
                                        <?php include_once $VIEW_PATH_INCLUDE . "WebSite/ReportBtn.phtml"; ?>

                                    </div>
                                </div>

                            </div>
                            <!-- Detail Info -->
                        </div>
                    </div>
                    <div class="product-info">
                        <div class="tab-style3">
                            <ul class="nav nav-tabs text-uppercase">

                                <li class="nav-item">
                                    <a class="nav-link active" id="Additional-info-tab" data-bs-toggle="tab" href="#Additional-info">Additional info</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="Vendor-info-tab" data-bs-toggle="tab" href="#Vendor-info">Vendor</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="Reviews-tab" data-bs-toggle="tab" href="#Reviews">Reviews (<?= $datas->total_review ?>)</a>
                                </li>
                            </ul>
                            <div class="tab-content shop_info_tab entry-main-content ">

                                <div class="tab-pane fade show active" id="Additional-info">
                                    <table class="font-md">
                                        <tbody>
                                            <tr class="stand-up">
                                                <th>Active Ingredients</th>
                                                <td>
                                                    <p> <?= ($datas->active_ingredients) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="folded-wo-wheels">
                                                <th>Age Range</th>
                                                <td>
                                                    <p> <?= ($datas->age_range) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="folded-w-wheels">
                                                <th>Item Dimensions</th>
                                                <td>
                                                    <p><?= ($datas->item_dimensions) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="door-pass-through">
                                                <th>Item Form</th>
                                                <td>
                                                    <p><?= ($datas->item_form) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="frame">
                                                <th>Hair Type</th>
                                                <td>
                                                    <p><?= ($datas->hair_type) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="weight-wo-wheels">
                                                <th>Liquid Volume</th>
                                                <td>
                                                    <p><?= ($datas->liquid_volume) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="weight-capacity">
                                                <th>Skin type</th>
                                                <td>
                                                    <p><?= ($datas->skin_type) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="width">
                                                <th>Special Ingredients</th>
                                                <td>
                                                    <p><?= ($datas->special_ingredients) ?></p>
                                                </td>
                                            </tr>
                                            <tr class="handle-height-ground-to-handle">
                                                <th>Product Benefits</th>
                                                <td>
                                                    <p><?= ($datas->benefits) ?></p>
                                                </td>
                                            </tr>





                                        </tbody>
                                    </table>
                                </div>
                                <div class="tab-pane fade " id="Vendor-info">
                                    <div class="vendor-logo d-flex mb-30">
                                        <img src="<?= $logo ?>" class="midel-size-radus" alt="<?= $datas->display_name ?>" />
                                        <div class="vendor-name ml-15">
                                            <h6>
                                                <a href="<?= $URL_Domain ?><?= $datas->display_name_slug ?>"><?= $datas->display_name ?></a>
                                            </h6>
                                            <div class="product-rate-cover text-end">
                                                <div class="product-rate d-inline-block">
                                                    <div class="product-rating" style="width: <?= intval($datas->Rating_business) * 20 ?>%"></div>
                                                </div>
                                                <span class="font-small ml-5 text-muted"> (<?= $datas->total_rate_business ?> reviews)</span>
                                            </div>
                                        </div>
                                    </div>
                                    <ul class="contact-infor mb-50">
                                        <li><img src="<?= $VIEW_PATH ?>assets/imgs/theme/icons/category-1.svg" alt="<?= $datas->display_name ?>" /><strong></strong> <span><?= $datas->more_info ?></span></li>
                                        <li><img src="<?= $VIEW_PATH ?>assets/imgs/theme/icons/icon-contact.svg" alt="<?= $datas->display_name ?>" /><span><?= $datas->telephone ?></span></li>
                                    </ul>

                                </div>
                                <div class="tab-pane fade " id="Reviews">
                                    <!--Comments-->
                                    <div class="comments-area">
                                        <div class="row">
                                            <div class="col-lg-8">
                                                <h4 class="mb-30">Customer questions & answers
                                                   <button id="btnReview" data-id="<?= $datas->id ?>" class="btn  mb-2">
                                                         Submit your review
                                                    </button>
                                                </h4>
                                                
                                                <div class="comment-list" id="comments">

                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12 text-center">
                                                        <button id="LoadMoreComment" class="btn-them" style="display: none;">Load More</button>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4">
                                                <h4 class="mb-30">Customer reviews</h4>
                                                <div class="d-flex mb-30">
                                                    <div class="product-rate d-inline-block mr-15">
                                                        <div class="product-rating" style="width: <?= intval($datas->Rating) * 20 ?>%"></div>
                                                    </div>
                                                    <h6><?= number_format((float)$datas->Rating, 1, '.', '') ?> out of 5</h6>
                                                </div>
                                                <div class="progress">
                                                    <span>5 star</span>
                                                    <div class="progress-bar" role="progressbar" style="width: <?= ($datas->Rating5 * 10) / 100 ?>%" aria-valuenow="<?= $datas->Rating5 ?>" aria-valuemin="0" aria-valuemax="100">
                                                        <?= $datas->Rating5 ?>%
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <span>4 star</span>
                                                    <div class="progress-bar" role="progressbar" style="width: <?= ($datas->Rating4 * 10) / 100 ?>%" aria-valuenow="<?= $datas->Rating4 ?>" aria-valuemin="0" aria-valuemax="100">
                                                        <?= $datas->Rating4 ?>%
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <span>3 star</span>
                                                    <div class="progress-bar" role="progressbar" style="width: <?= ($datas->Rating3 * 10) / 100 ?>%" aria-valuenow="<?= $datas->Rating3 ?>" aria-valuemin="0" aria-valuemax="100">
                                                        <?= $datas->Rating3 ?>%
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <span>2 star</span>
                                                    <div class="progress-bar" role="progressbar" style="width: <?= ($datas->Rating2 * 10) / 100 ?>%" aria-valuenow="<?= $datas->Rating2 ?>" aria-valuemin="0" aria-valuemax="100">
                                                        <?= $datas->Rating2 ?>%
                                                    </div>
                                                </div>
                                                <div class="progress mb-30">
                                                    <span>1 star</span>
                                                    <div class="progress-bar" role="progressbar" style="width: <?= ($datas->Rating1 * 10) / 100 ?>%" aria-valuenow="<?= $datas->Rating1 ?>" aria-valuemin="0" aria-valuemax="100">
                                                        <?= $datas->Rating1 ?>%
                                                    </div>
                                                </div>

                                                <button id="btnRate" data-cat="<?= $datas->catagories ?>" data-id="<?= $datas->id ?>" class="btn-them">Rate this product</button>

                                            </div>
                                        </div>
                                    </div>
                                    <!--comment form-->

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-60">
                        <div class="col-12">
                            <h2 class="section-title style-1 mb-30">Related products</h2>
                        </div>
                        <div class="col-12">
                            <div class="row related-products">
                                <?php
                                $relates = $data['relates'];
                                $type = "product";
                                include $VIEW_PATH_INCLUDE . "WebSite/Relates.phtml";
                                ?>

                                <!-- <div class="col-lg-3 col-md-4 col-12 col-sm-6 d-lg-block d-none">
                                    <div class="product-cart-wrap hover-up mb-0">
                                        <div class="product-img-action-wrap">
                                            <div class="product-img product-img-zoom">
                                                <a href="shop-product-right.html" tabindex="0">
                                                    <img class="default-img" src="<?= $VIEW_PATH ?>assets/imgs/shop/product-5-1.jpg" alt="" />
                                                    <img class="hover-img" src="<?= $VIEW_PATH ?>assets/imgs/shop/product-3-2.jpg" alt="" />
                                                </a>
                                            </div>
                                            <div class="product-action-1">
                                                <a aria-label="Quick view" class="action-btn small hover-up" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-search"></i></a>
                                                <a aria-label="Add To Wishlist" class="action-btn small hover-up" href="shop-wishlist.html" tabindex="0"><i class="fi-rs-heart"></i></a>
                                                <a aria-label="Compare" class="action-btn small hover-up" href="shop-compare.html" tabindex="0"><i class="fi-rs-shuffle"></i></a>
                                            </div>
                                            <div class="product-badges product-badges-position product-badges-mrg">
                                                <span class="hot">Hot</span>
                                            </div>
                                        </div>
                                        <div class="product-content-wrap">
                                            <h2><a href="shop-product-right.html" tabindex="0">Dadua Camera 4K 2021EF</a></h2>
                                            <div class="rating-result" title="90%">
                                                <span> </span>
                                            </div>
                                            <div class="product-price">
                                                <span>$89.8 </span>
                                                <span class="old-price">$98.8</span>
                                            </div>
                                        </div>
                                    </div>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>