    <div class="">
        <div class=" row mt-3 mb-3 ms-1 me-1 mr-1 p-1">
            <?php if ($data['category_search'] == 'true') { ?>
                <div class="col-md-12 border-bottom">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Category:</label>
                        <div data-dismiss="modal" type="text" class="form-control p-3 category point" id="category_id"></div>
                        <input type="text" hidden="" class="form-control point " id="catagories_id">

                    </div>
                </div>
            <?php } ?>
            <div class="col-md-12 border-bottom">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Title:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="titles2">
                </div>
            </div>
            <div class="col-md-12 border-bottom">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Sort:</label>
                    <select id="orders2" class="form-control ">
                        <option value=""></option>
                        <option value="id,desc">The Newest</option>
                        <option value="id,asc">The Oldest</option>
                        <option value="title,asc">A-Z</option>
                        <option value="title,desc">Z-A</option>
                    </select>
                </div>
            </div>

            <?php if (isset($data['program_search'])) { ?>
                <div class="col-md-12 border-bottom ">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Program Type:</label>
                        <select id="typeP1" class="form-control ">
                            <option value=""></option>

                        </select>
                    </div>
                </div>
                <div class="col-md-12 border-bottom ">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Category:</label>
                        <select id="categoryP1" class="form-control ">
                            <option value=""></option>

                        </select>
                    </div>
                </div>
                <!-- <div class="col-md-12 border-bottom ">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Award Section:</label>
                        <select id="awardP1" class="form-control ">
                            <option value=""></option>

                        </select>
                    </div>
                </div> -->
            <?php } ?>

            <?php if (isset($data['have_price'])) { ?>
                <div class="col-md-12 border-bottom">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Price:</label>
                        <label class="radiobox">$0.0-$65.0
                            <input type="radio" value="0-65" name="price" id="price">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox">$65.0-$110.0
                            <input type="radio" value="65-110" name="price" id="price2">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox">$110.0-$175.0
                            <input type="radio" value="110-175" name="price" id="price3">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox">$175.0-$300.0
                            <input type="radio" value="175-300" name="price" id="price4">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox">$300.0+
                            <input type="radio" value="300" name="price" id="price5">
                            <span class="chmr"></span>
                        </label>

                    </div>
                </div>
            <?php } ?>

            <?php if (isset($data['have_rating'])) { ?>
                <div class="col-md-12 border-bottom">
                    <div class="mb-3 ">
                        <label for="recipient-name" class="col-form-label">Rating:</label>
                        <label class="radiobox text-warning ">
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star"></i>
                            <input type="radio" value="4" name="rate" id="rate">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox text-warning">
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star"></i>
                            <i class="bi bi-star"></i>
                            <input type="radio" value="3" name="rate" id="rate2">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox text-warning">
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star"></i>
                            <i class="bi bi-star"></i>
                            <i class="bi bi-star"></i>
                            <input type="radio" value="2" name="rate" id="rate3">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox text-warning">
                            <i class="bi bi-star-fill"></i>
                            <i class="bi bi-star"></i>
                            <i class="bi bi-star"></i>
                            <i class="bi bi-star"></i>
                            <i class="bi bi-star"></i>
                            <input type="radio" value="1" name="rate" id="rate4">
                            <span class="chmr"></span>
                        </label>
                   

                    </div>
                </div>
            <?php } ?>

     
            <div class="col-md-12  text-center mb-5 mt-5">
                <button class="btn btn-prim SearchBtn inp-enter" >search</button>
                <button class="btn resetBtn" >Reset</button>
            </div>
        </div>
    </div>