<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16">
        <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
    </svg>
    <span class="ml-3">Coupon</span>

</div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Coupon List
        <input type="checkbox" id="ch_fo1" name="listm" value="fo1,couponp">
        <span class="checkmark"></span>
    </label>

</div>
<div class="col-md-4 mt-3 ">

    <label class="chboxs ">Add
        <input type="checkbox" id="fo1_add" name="modul" value="add,fo1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs col-md-3">Edit
        <input type="checkbox" name="modul" id="fo1_edit" value="edit,fo1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Image
        <input type="checkbox" name="modul" id="fo1_image" value="image,fo1">
        <span class="checkmark"></span>
    </label>
</div>
<div class="col-md-5 mt-3">
     <label class="chboxs ">Send To Top List
        <input type="checkbox" name="modul" id="fo1_top" value="top,fo1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Remove
        <input type="checkbox" name="modul" id="fo1_remove" value="remove,fo1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Code
        <input type="checkbox" name="modul" id="fo1_code" value="code,fo1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Send To Admin
        <input type="checkbox" name="modul" id="fo1_admin" value="admin,fo1">
        <span class="checkmark"></span>
    </label>
    <!-- <label class="chboxs ">View
        <input type="checkbox" name="modul" id="fo1_view" value="view,fo1">
        <span class="checkmark"></span>
    </label>  -->
</div>

<hr>
<div class="col-md-3 mt-3">

    <label class="chboxs">Sale List
        <input type="checkbox" name="listm" id="ch_fo2" value="fo2,couponp">
        <span class="checkmark"></span>
    </label>

</div>