<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16">
        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
    </svg>
    <span class="ml-3">Product</span>

</div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Product List
        <input type="checkbox" id="ch_pr1" name="listm" value="pr1,productsp">
        <span class="checkmark"></span>
    </label>

</div>
<div class="col-md-4 mt-3 ">

    <label class="chboxs ">Add
        <input type="checkbox" id="pr1_add" name="modul" value="add,pr1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs col-md-3">Edit
        <input type="checkbox" id="pr1_edit" name="modul" value="edit,pr1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Image
        <input type="checkbox" id="pr1_image" name="modul" value="image,pr1">
        <span class="checkmark"></span>
    </label>
</div>
<div class="col-md-5 mt-3">
<label class="chboxs ">Gallery
        <input type="checkbox" id="pr1_gallery" name="modul" value="gallery,pr1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Send To Top List
        <input type="checkbox" id="pr1_top" name="modul" value="top,pr1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Remove
        <input type="checkbox" id="pr1_remove" name="modul" value="remove,pr1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">View
        <input type="checkbox" id="pr1_view" name="modul" value="view,pr1">
        <span class="checkmark"></span>
    </label>
</div>

