<div class="modal fade bd-example-modal-lg" id="modalCategory" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Choose your category </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
              <div id="category_data" class="row p-2 m-2">
                  
              </div>
            </div>

            <div class="modal-footer-glass modal-footer">

            </div>
        </div>
    </div>
</div>