<div class="modal fade bd-example-modal-lg" id="modalRemove" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Are Youe Soure?  </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmRemove">
                <div class="mb-3">
                        <label class="radiobox">Delete
                            <input type="radio" checked value="disabled" name="delete_type" id="delete_type">
                            <span class="chmr"></span>
                        </label>
                        <!-- <label class="radiobox">Delete
                            <input type="radio" value="delete" name="delete_type" id="delete_type">
                            <span class="chmr"></span>
                        </label> -->
            
                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-action="" data-rmoveid=""  data-id="modalRemove" id="removeBtn" class="btn  btn-glass">Apply</button>
             
            </div>
        </div>
    </div>
</div>