<div class=" m-top">
 
  

    <div class="covers p-1">
        <form id="frmNew">
         
            <div class="mb-3">

                <textarea name="editors"></textarea>
            </div>
        </form>
        <div class="row">
            <div class="col-md-12 mt-4 mb-5 text-center">
                <button id="addNew" class="btn btn-prim">Save</button>
            </div>
        </div>
    </div>

</div>