<?php
include_once($VIEW_PATH_ADMIN_INCLUDE . "Setting/modal/AddAdmin.phtml");
include_once($VIEW_PATH_ADMIN_INCLUDE . "Setting/modal/EditAdmin.phtml");
include_once($VIEW_PATH_ADMIN_INCLUDE . "Setting/modal/PermissionMenu.phtml");
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/RemoveAdmin.phtml";
?>
<div class="covers m-top">

    <div class="covers mb-3">
        <form id="searchfrm">
            <div class="row">
                <div class="col-md-12 mb-2">
                    <small id="addNewBtn" class="btn btn-prim btn-lg ">
                        <i class="bi bi-plus-lg mr-2"></i> Add Admin
                    </small>
                </div>
                <div class="col-md-4">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">ID:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> Name:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="names">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> User Name:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="usernames">
                    </div>
                </div>
     



                <div class="col-md-12 mb-2 text-center">
                    <button type="button" id="searchbtn" class="btn btn-prim btn-lg">
                        <i class="bi bi-search mr-2"></i> Search
                    </button>
                    <button id="reset" type="button" class="btn  btn-lg">
                        Reset
                    </button>
                </div>
            </div>
        </form>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Username</th>
                <th>Password</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>