<?php
include_once($VIEW_PATH_ADMIN_INCLUDE . "Setting/modal/AddAdmin.phtml");
include_once($VIEW_PATH_ADMIN_INCLUDE . "Setting/modal/EditAdmin.phtml");
include_once($VIEW_PATH_ADMIN_INCLUDE . "Setting/modal/PermissionMenu.phtml");
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/RemoveAdmin.phtml";
?>
<div class="covers m-top">

    <div class="covers mb-3">
        <form id="searchfrm">
            <div class="row">
                <div class="col-md-12 mb-2">
                    <a href="<?= $URL_Domain ?>AddAnnouncement" class="btn btn-prim btn-lg ">
                        <i class="bi bi-plus-lg mr-2"></i> Add
                    </a>
                </div>






            </div>
        </form>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>description</th>
                <th>Is online</th>
                <th>All user</th>
                <th>Users</th>
                <th>Cites</th>
                <th>Type</th>
                <th>Expire</th>
                <!-- <th>Action</th> -->
            </tr>
        </thead>

    </table>
</div>