
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Title:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="title" name="title">
</div>

<div class="mb-3 " id="more_cat"></div>

<div class="mb-3 row" id="more_link">
    <div class="col-md-4">
        <label for="recipient-name" class="col-form-label">Link type:</label>
        <select id="ltype1" class="form-control min-radus select-css ">
            <option value=""></option>
            <option value="link">Link</option>
            <option value="video">Video</option>

        </select>
    </div>
    <div class="col-md-4">
        <label for="recipient-name" class="col-form-label">Link Title:</label>
        <input id="ltitle1" type="text" autocomplete="off" class="form-control min-radus ">
    </div>
    <div class="col-md-4">
        <label for="recipient-name" class="col-form-label">Link Address:</label>
        <input id="ltag1" type="text" autocomplete="off" class="form-control min-radus ">
    </div>

</div>

<div class="mb-3">
    <button type="button" id="add_more_links" data-id="more_link" class="btn btn-glass">Add More</button>
</div>


<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Description:</label>
    <textarea rows="5" class="form-control min-radus " id="descriptions" name="descriptions"></textarea>
</div>

