<div class="m-1 covers">
    <div class="row" id="images">

    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="mb-3">
                <input type="file" accept=".png, .jpg, .jpeg" multiple name="file_img" id="file_img" class="fileinputs">

            </div>
        </div>
    </div>
    <diw class="row">
        <div class="col-md-12 text-center">
            <button class="btn btn-prim btn-lg" id="saveBtn">Save</button>
        </div>
    </diw>
</div>