<div class="modal fade bd-example-modal-lg" id="ModalAddTop" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Add To Top List</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="addTopFrm">

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> Type:</label>
                        <select class="form-control min-radus " id="typeAd" name="type">
                            <option value=""></option>
                            <option value="click">Click</option>
                            <option value="show">Show</option>
                        </select>
                    </div>


                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">number:</label>
                        <input type="number" autocomplete="off" class="form-control min-radus " id="numbers" name="numbers">
                    </div>



                </form>

                <div class="m-4 row" id="result_top"></div>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-editid="" data-id="ModalAddTop" id="btnAddTop" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>