<div class="modal fade bd-example-modal-lg" id="ModalEdit" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Edit Prize</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmEdit">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Title:</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " id="title_e" name="title">
                        <input type="text" name="idSearch" id="idSearch" hidden>
                    </div>


                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Value:</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " id="jvalues_e" name="jvalues">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Number of inventory:</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " id="jnumber_e" name="jnumber">
                    </div>


                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Description:</label>
                        <textarea rows="5" class="input-white min-radus " id="description_e" name="description"></textarea>
                    </div>
                    <?php
                    if (isset($admin)) {
                        include $VIEW_PATH_INCLUDE . "UserDashboard/User/delete/removeAdmin.phtml";
                    } else {
                        include $VIEW_PATH_INCLUDE . "UserDashboard/User/delete/remove.phtml";
                    }
                    ?>

                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-id="ModalEdit" id="btnSaveEdit" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>