<div class="modal fade bd-example-modal-lg" id="modalSendHome" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Show at the Home Page </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmHomeShow">
                <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">choose type :</label>
                        <label class="radiobox">Add To Home page
                            <input type="radio" checked value="add" name="type_show" id="type_show">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox">Delete From Home page
                            <input type="radio" value="delete" name="type_show" id="type_show">
                            <span class="chmr"></span>
                        </label>
            
                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button"  data-id="modalSendHome" id="saveHomeShowBtn" class="btn  btn-glass">Apply</button>
             
            </div>
        </div>
    </div>
</div>