
<div class="covers">

 
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Comment</th>
                <th>Forum</th>
                <th>Like</th>
                <th>Date</th>
            </tr>
        </thead>

    </table>
</div>