<div class="modal fade bd-example-modal-lg" id="ModalAdd" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Value</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">

                <form id="newFrm">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> Value (separate with new line)</label>
                        <textarea name="value" id="value" class="form-control" rows="10"></textarea>
                    </div>

                </form>
            </div>
            <div class="modal-footer-glass modal-footer">
                <button data-id="ModalAdd" id="btnNew" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>