<div class="modal fade bd-example-modal-lg" id="ModalView" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="row text-start">
                    <div class="col-md-12  mb-2 p-1" id="img">

                    </div>
                    <div class="col-md-12 text-center mb-1 h5" id="title">

                    </div>

                    <div class="col-md-12 p-1 mb-1" id="category">

                    </div>
                    <div class="col-md-12 p-1 mb-1" id="city">

                    </div>
                    <div class="col-md-12 p-1 mb-1" id="links">

                    </div>

                    <div class="col-md-12 p-1 mb-1" id="date">

                    </div>
                    <div class="col-md-12 p-1 mb-1" id="inventory">

                    </div>
                    <div class="col-md-12 p-1 mb-1" id="price">

                    </div>

                    <div class="col-md-12 p-1 mb-1" id="product_price">

                    </div>
                    <div class="col-md-12 p-1 mb-1" id="deal_product_price">

                    </div>
                    <div class="col-md-12 p-1 mb-1">
                        <p id="description"></p>
                    </div>
                </div>

            </div>
            <div class="modal-footer-glass modal-footer">
            </div>
        </div>
    </div>
</div>