<?php
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Remove.phtml";
   include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Coupon/modal/EditImage.phtml";
   include_once $VIEW_PATH_INCLUDE."BusinessDashboard/modal/AddToTop.phtml";
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Category.phtml";
   include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Deals/modal/ViewData.phtml";

?>
<div class="covers">

    <div class="covers m-top mb-3">
        <div class="row">
            <div class="col-md-12 mb-2">
                <a href="<?=$URL_Domain?>AddDeals" class="btn btn-prim btn-lg ">
                    <i class="bi bi-plus-lg mr-2"></i> Add Deals
                </a>
            </div>

            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">ID:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Title:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="titlese">
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <div id="more_cat"></div>
                </div>
            </div>
            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Value</th>
                <th>Price</th>
                <th>product</th>
                <th>Start</th>
                <th>expire</th>
                <th>Number</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>