<?php

include_once $VIEW_PATH_INCLUDE . "BusinessDashboard/Deals/modal/Add.phtml";
include_once $VIEW_PATH_INCLUDE . "BusinessDashboard/Deals/modal/UpdateLinkCode.phtml";

?>
<div class="covers">
    <div class="mb-4">
        <span class="sm-font">
            <a href="<?= $URL_Domain ?><?= $data['listHref'] ?>"><?= $data['list'] ?></a>
        </span>
        <span class="sm-font"><i class="bi bi-chevron-right"></i></span>
        <span class="sm-font"><?= $data['page_name'] ?></span>
    </div>

    <div class="covers m-top mb-3">
        <div class="row">
            <div class="col-md-12 mb-2">
                <small id="BtnAdd" class="btn btn-prim btn-lg ">
                    <i class="bi bi-plus-lg mr-2"></i> Add Link Or Code
                </small>
            </div>

            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">ID:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Title:</label>
                    <input type="text" autocomplete="off" class="form-control min-radus " id="titlese">
                </div>
            </div>

            <div class="col-md-12 mb-2 text-center">
                <button id="searchbtn" class="btn btn-prim btn-lg">
                    <i class="bi bi-search mr-2"></i> Search
                </button>
            </div>
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Value</th>
                <th>How many times can it be used</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>