<div class="mb-3 " id="more_cat<?=$edit?>"></div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Title:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="title<?=$edit?>" name="title">
</div>


<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Search Product:</label>
    <select style="width: 100%" class="input-white min-radus  productSearch select-css" multiple name="product_id" id="product_id<?=$edit?>">

    </select>

</div>
<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> type:</label>
    <select class="form-control min-radus"  name="type" id="type<?=$edit?>"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Value:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="amount<?=$edit?>" name="amount">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Product Price:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="product_price<?=$edit?>" name="product_price">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Deal Product Price:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="deal_product_price<?=$edit?>" name="deal_product_price">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Price:</label>
    <input type="text" autocomplete="off" class="form-control min-radus " id="price<?=$edit?>" name="price">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> How many can be used:</label>
    <input type="number" autocomplete="off" class="form-control min-radus " name="inventory" id="inventory<?=$edit?>">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Start Date:</label>
    <input type="date" autocomplete="off" class="form-control min-radus " name="start" id="start<?=$edit?>">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span> Expire Date:</label>
    <input type="date" autocomplete="off" class="form-control min-radus " name="expire" id="expire<?=$edit?>">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Description:</label>
    <textarea rows="5" class="form-control min-radus "  name="description" id="description<?=$edit?>"></textarea>
</div>