
<div class="d-flex justify-content-center">
    <div class="  m-top" style="width: 50%;">

        <div class="row mt-5 border-left border-right border-bottom">
            <div class="col-md-12 row border-bottom align-items-center p-2">
                <div class="col-md-2 border-right p-2">
                    <?php if ($data['imageBuyer'] != '') { ?>
                        <?=$data['imageBuyer']?>
                    <?php } ?>
                </div>
                <div class="col-md-10 p-2 text-center">
                    <h4><?= $data['BuyerName'] ?></h4>
                </div>
            </div>
            <div class="col-md-12 text-center text-info border-bottom p-2 h5">
                <strong><?= $data['code'] ?></strong>
            </div>
            <br>
            
            <?php if($data['product_title']!=""){?>
            <div class="col-md-12 text-center border-bottom p-2">
               <strong>Product: <?= $data['product_title'] ?></strong>
            </div>
            <?php }?>
            <br>
            <div class="col-md-12  p-2 border-bottom">
                <span> <?= $data['description'] ?></span>
            </div>
            <br>
            <div class="col-md-12 text-center p-2">
                <p>Expire in <?= $data['expire'] ?></p>
            </div>

            <div class="col-md-12  p-2">
                <?= $SiteName ?>
            </div>
        </div>
    </div>
</div>