<div class="mb-3 row">
    <label for="recipient-name" class="col-form-label">Select a city or select an online option for all cities</label>


    <div class="col-md-3">

        <select style="width: 100%;" name="country_id" id="country_id<?=$edit?>" class="form-control select2<?=$edit?>">

        </select>
    </div>
    <div class="col-md-3">
        <select style="width: 100%;" name="province_id" id="province_id<?=$edit?>" class="form-control select2<?=$edit?>"></select>
    </div>
    <div class="col-md-3">
        <select style="width: 100%;" name="city_id" id="city_id<?=$edit?>" class="form-control select2<?=$edit?>"></select>
    </div>
    <div class="col-md-3">
    <label for="recipient-name" class="col-form-label">Street</label>
        <input type="text"  class="from-control" name="street" id="street">
    </div>
</div>