<?php


if ($d->file_url !== "" && $d->file_url !== null) {
    $imgurl = $URL_PATH . $d->file_url . '/small/' . $d->file_name;
} else {
    $imgurl = $VIEW_PATH . "imgs/defult.jpg";
}
// $class_img = "";
// if (isset($set_img_class) && $set_img_class) {

//     $class_img = "img-sam-size";
// }
$class_img = "img-sam-size";
?>
<a href="<?= $URL_Domain ?><?= $data['url'] ?>/<?= $d->title_slug ?>" class="hrefs col-md-4">
    <div class="card-contain  m-1 ">
        <div class="card-image position-relative">
            <img src="<?= $imgurl ?>" alt="<?= $d->title ?>" class="<?= $class_img ?>">
            <div class="img-over-top bag-defult top-r-b-l-radus"><?= $d->program_type ?></div>
        </div>
        <div class="card-details text-muted">
            <div class="card-title"><?= $d->title ?></div>
            <div class="mt-1 ">
                <div>
                    <span>Guest : </span>
                    <?php
                    $guest = explode(",", $d->program_guests);
                    foreach ($guest as $g) {
                        $guest_item = explode("::", $g);
                        $name = "";
                        if ($guest_item[1] != '')
                            $name = $guest_item[1];
                        if ($guest_item[3] != '')
                            $name = $guest_item[3];
                        if ($guest_item[4] != '')
                            $name = $guest_item[4]; ?>
                        <span><?= $name ?></span><span> </span>
                    <?php } ?>
                </div>
                <div class=" p-1">
                    <span class="text-muted"><?= substr($d->description, 0, 100) . '...' ?></span>
                </div>
            </div>
        </div>
    </div>
</a>