<?php


?>
<div class="covers">

    
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Company</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Description</th>
         
       
            </tr>
        </thead>

    </table>
</div>