<?php


 ?>
<div class="covers m-top">

    <div class="covers mb-3">
        <form id="searchFrm">
            <div class="row">
            <div class="col-md-12 mb-2">
            
            </div>
                <div class="col-md-4">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">ID:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Title:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="titles">
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Business:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="nameS">
                    </div>
                </div>

              <div class="col-md-12 mb-2 text-center">
                    <button type="button" id="searchbtn" class="btn btn-prim btn-lg">
                        <i class="bi bi-search mr-2"></i> Search
                    </button>
                 
                </div>
            </div>
        </form>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Business</th>
                <th>Amount paid</th>
                <th>Clearing Date</th>
                <th>ّFiles</th>
            </tr>
        </thead>

    </table>
</div>