<?php
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/Category.phtml";
?>
<div class="m-top covers text-dark">
    <div class="mb-4">
        <span class="sm-font">
            <a href="<?= $URL_Domain ?><?= $data['listHref'] ?>"><?= $data['list'] ?></a>
        </span>
        <span class="sm-font"><i class="bi bi-chevron-right"></i></span>
        <span class="sm-font">Edit Profile</span>
    </div>
    <form id="frmNew">
        <input type="text" name="idSearch" hidden id="idSearch">
        <?php
        $edit = "";
        include $VIEW_PATH_INCLUDE . "BusinessDashboard/User/ProfileModal/Item.phtml"; ?>
        <div class="mb-3">
            <label for="recipient-name" class="col-form-label">About:</label>
            <textarea type="date" autocomplete="off" class="input-white min-radus " id="about" name="about"></textarea>
        </div>

        <?php if ($data['showRemove'] == 'true') {
            include $VIEW_PATH_INCLUDE . "UserDashboard/User/delete/removeAdmin.phtml";
        }  ?>


    </form>
    <div class="row mt-4 mb-4">
        <div class="col-md-12 text-center">
            <button id="btnAddNew" type="button" class="btn btn-lg btn-prim">Save</button>

        </div>
    </div>
</div>