<?php
$btn_title="Set Prize";
$admin=true;
include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/RemoveAdmin.phtml";
include_once $VIEW_PATH_INCLUDE."Admin/modal/SetPrize.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Prize/modal/EditInfo.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Prize/modal/EditImage.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Prize/modal/ViewData.phtml";

include_once $VIEW_PATH_ADMIN_INCLUDE . "Tables/View4.phtml";
?>