<div class="modal fade bd-example-modal-lg" id="ModalAddProject" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Project</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="projectfrm">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Title:</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " id="title" name="title">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Category:</label>
                        <div data-dismiss="modal" type="text"  class="input-white min-radus point" id="category_id"></div>
                        
                    </div>

                    <div class="mb-3 row">
                        <div class="col-md-6">
                        <label for="recipient-name" class="col-form-label">Link Title:</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " id="title_link" name="title_link">
                        </div>
                        <div class="col-md-6">
                        <label for="recipient-name" class="col-form-label">Link Address:</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " id="tag" name="tag">
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Description:</label>
                        <textarea rows="5" class="input-white min-radus " id="description" name="description"></textarea>
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label ">skills:</label>
                        <select data-url="fetchData/getSkill" style="width: 100%" class="input-white min-radus tokenize select-css" multiple name="propf_id" id="propf_id">

                        </select>

                    </div>

                    <div class="mb-3">
                    <input type="file"  accept=".png, .jpg, .jpeg" name="project_image" id="project_image" class="fileinputs">


                    </div>


                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-editid="" data-id="ModalAddProject" id="btnproject" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>