
    
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Country Name:</label>
        <select style="width: 100%;" name="country_id" id="country_id<?=$edit?>"  class="form-control select2<?=$edit?>"></select>
    </div>

    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Province Name:</label>
        <select style="width: 100%;" name="province_id" id="province_id<?=$edit?>"  class="form-control select2<?=$edit?>"></select>
    </div>
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Title:</label>
        <input type="text" autocomplete="off" class="form-control min-radus " name="name" id="name<?=$edit?>">
    </div>



