
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Title:</label>
        <input type="text" autocomplete="off" class="form-control min-radus " name="name" id="name<?=$edit?>">
    </div>


    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Sort Name:</label>
        <input type="text" autocomplete="off" class="form-control min-radus " name="sort_name" id="sort_name<?=$edit?>">
    </div>

    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Phone Code:</label>
        <input type="text" autocomplete="off" class="form-control min-radus " name="phone_code" id="phone_code<?=$edit?>">
    </div>