<div class="modal fade bd-example-modal-lg" id="modalReview" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Review </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmNewReview">
                   
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> your comment</label>
                        <textarea rows="5" class="form-control" name="text" id="text"></textarea>
                    </div>
                    <?php include $VIEW_PATH_INCLUDE . "Captcha.html";?>

                </form>

            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-table="<?= $table ?>" data-item="<?= $item_id ?>" data-id="modalReview" id="addReview" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>