<div class="modal fade bd-example-modal-lg" id="modalReport" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Report  </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmNewReport">
                <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">choose report type :</label>
                        <?php foreach($report as $rp){?>
                        <label class="radiobox"><?=$rp->title?>
                            <input type="radio"  value="<?=$rp->id?>" name="proof_id" id="report">
                            <span class="chmr"></span>
                        </label>
                        <?php }?>
                  
                        <?php include $VIEW_PATH_INCLUDE . "Captcha.html";?>

                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-table="<?=$table?>" data-item="<?=$item_id?>"   data-id="modalReport" id="addreport" class="btn  btn-glass">Save</button>
             
            </div>
        </div>
    </div>
</div>