<div class="modal fade bd-example-modal-lg" id="modalReview" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Review </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmNewReview">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"><span class="text-danger">*</span>Have you bought this product?</label>
                        <select class="form-control" name="bought" id="boughtReview">
                            <option></option>
                            <option value="1">Yes</option>
                            <option value="0">No</option>
                        </select>
                    </div>
                    <div id="storDivR" style="display:none" class="mb-3">
                        <label for="recipient-name" class="col-form-label">Search for the store you bought and if it is not found, type it and press Enter:</label>
                        <select style="width: 100%" class="form-control min-radus  tokenize-custom-demo1 " multiple id="storeR">
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> your comment</label>
                        <textarea rows="5" class="form-control" name="text" id="text"></textarea>
                    </div>
                    <?php include $VIEW_PATH_INCLUDE . "Captcha.html";?>

                </form>

            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-table="<?= $table ?>" data-item="<?= $item_id ?>" data-id="modalReview" id="addReview" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>