<div class="modal fade bd-example-modal-lg" id="ModalView" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Information </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="row ">

                    <div class="col-md-12 text-center mb-1" id="title_view">

                    </div>


                    <div class="ms-1 col-md-12 p-1 mb-1" id="Links">

                    </div>

                    <div class="ms-1 col-md-12 p-1 mb-1" id="price">

                    </div>


                    <div class="ms-1 col-md-12 p-1 mb-1">
                        <p id="description_view"></p>
                    </div>

                    <div id="img_gallery" class=" col-md-12 gallery mt-2 mb-2 p-5">
                    </div>
                </div>

            </div>
            <div class="modal-footer-glass modal-footer">
            </div>
        </div>
    </div>
</div>