<div id="profSidemenu" class="sidepanel  ">
    <div class="closebtn" id="closeNavProf">×</div>
    <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="bi bi-house-fill"></i> </div>
        <div class="tag-side-menu">
            <a href="<?=$URL_Domain?>">Home</a>
        </div>
    </div>

    <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="bi bi-person-badge-fill"></i> </div>
        <div class="tag-side-menu">
            <a href="<?=$URL_Domain?>BusinessProfile">profile</a>
        </div>
    </div>

    <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="bi bi-bell-fill"></i></div>
        <div class="tag-side-menu">
            <a href="<?=$URL_Domain?>MyNotification"><span class="text-danger" id="side_profile_note"></span> Notification</a>
        </div>
    </div>


    <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="fas fa-sign-out-alt"></i> </div>
        <div class="tag-side-menu">
            <a href="<?=$URL_Domain?>LogOutBusinessUser">Log out</a>
        </div>
    </div>

</div>