<link rel="stylesheet" href="<?= $VIEW_PATH ?>css/UserDashboard/Layout/SideMenu.css">

<div id="sideBar" class="iq-sidebar   sidebar-default mt-4">

    <div class="data-scrollbar" data-scroll="1" data-scrollbar="true" tabindex="-1">
        <div class="scroll-content">
            <nav class="iq-sidebar-menu">
                <ul id="iq-sidebar-toggle" class="iq-menu">

                    <li class="active pl">
                        <a href="<?= $URL_Domain ?>BusinessUserDashboard" class="svg-icon ">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" width="20" height="20">
                                <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path>
                            </svg>
                            <span class="ml-3"> Dashboard</span>
                        </a>
                    </li>

                    <li class=" pl">
                        <a id="productsp" data-id="products" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16">
                                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                            </svg>
                            <span class="ml-3">Product</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="products" data-parentid="productsp" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>ProductList" class="sub-menu" data-parent="productsp">
                                    <i class="las la-minus"></i><span>Product List</span>
                                </a>
                            </li>
                        </ul>
                    </li>




                    <li class=" pl">
                        <a id="rewardsp" data-id="rewards" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gift" viewBox="0 0 16 16">
                                <path d="M3 2.5a2.5 2.5 0 0 1 5 0 2.5 2.5 0 0 1 5 0v.006c0 .07 0 .27-.038.494H15a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 1 14.5V7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h2.038A2.968 2.968 0 0 1 3 2.506V2.5zm1.068.5H7v-.5a1.5 1.5 0 1 0-3 0c0 .085.002.274.045.43a.522.522 0 0 0 .023.07zM9 3h2.932a.56.56 0 0 0 .023-.07c.043-.156.045-.345.045-.43a1.5 1.5 0 0 0-3 0V3zM1 4v2h6V4H1zm8 0v2h6V4H9zm5 3H9v8h4.5a.5.5 0 0 0 .5-.5V7zm-7 8V7H2v7.5a.5.5 0 0 0 .5.5H7z" />
                            </svg>
                            <span class="ml-3">Prize</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="rewards" data-parentid="rewardsp" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>PrizeList" class="sub-menu" data-parent="rewardsp">
                                    <i class="las la-minus"></i><span>Prize List</span>
                                </a>
                            </li>
                        </ul>
                    </li>



                    <li class=" pl">
                        <a id="Couponsp" data-id="Coupons" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16">
                                <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
                                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
                            </svg>
                            <span class="ml-3">Coupon</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="Coupons" data-parentid="Couponsp" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>CouponList" class="sub-menu" data-parent="Couponsp">
                                    <i class="las la-minus"></i><span>Coupon List</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?= $URL_Domain ?>SaleCouponList" class="sub-menu" data-parent="CouponsP">
                                    <i class="las la-minus"></i><span>Sale list</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="DealsP" data-id="Deals" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z" />
                                <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z" />
                                <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z" />
                                <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z" />
                            </svg>
                            <span class="ml-3">Deals</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="Deals" data-parentid="DealsP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>DealsList" class="sub-menu" data-parent="DealsP">
                                    <i class="las la-minus"></i><span>Deals List</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>ShoppingDealsList" class="sub-menu" data-parent="DealsP">
                                    <i class="las la-minus"></i><span>Sale list</span>
                                </a>
                            </li>
                            
                            <li class="">
                                <a href="<?= $URL_Domain ?>MyDealsClearedList" class="sub-menu" data-parent="DealsP">
                                    <i class="las la-minus"></i><span>Deals Cleared List</span>
                                </a>
                            </li>
                        </ul>
                    </li>


                    <li class=" pl">
                        <a id="jobP" data-id="Jobs" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-briefcase" viewBox="0 0 16 16">
                                <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v8A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1h-3zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5zm1.886 6.914L15 7.151V12.5a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5V7.15l6.614 1.764a1.5 1.5 0 0 0 .772 0zM1.5 4h13a.5.5 0 0 1 .5.5v1.616L8.129 7.948a.5.5 0 0 1-.258 0L1 6.116V4.5a.5.5 0 0 1 .5-.5z" />
                            </svg>
                            <span class="ml-3">Jobs</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="Jobs" data-parentid="jobP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>JobList" class="sub-menu" data-parent="jobP">
                                    <i class="las la-minus"></i><span>Job List</span>
                                </a>
                            </li>


                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="banners" data-id="banner" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-badge-ad" viewBox="0 0 16 16">
                                <path d="m3.7 11 .47-1.542h2.004L6.644 11h1.261L5.901 5.001H4.513L2.5 11h1.2zm1.503-4.852.734 2.426H4.416l.734-2.426h.053zm4.759.128c-1.059 0-1.753.765-1.753 2.043v.695c0 1.279.685 2.043 1.74 2.043.677 0 1.222-.33 1.367-.804h.057V11h1.138V4.685h-1.16v2.36h-.053c-.18-.475-.68-.77-1.336-.77zm.387.923c.58 0 1.002.44 1.002 1.138v.602c0 .76-.396 1.2-.984 1.2-.598 0-.972-.449-.972-1.248v-.453c0-.795.37-1.24.954-1.24z" />
                                <path d="M14 3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h12zM2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2z" />
                            </svg>
                            <span class="ml-3">Advertise with us</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="banner" data-parentid="banners" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>BannerOrder" class="sub-menu" data-parent="banners">
                                    <i class="las la-minus"></i><span>Banner Order</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>MySponsorShipOrder" class="sub-menu" data-parent="banners">
                                    <i class="las la-minus"></i><span>SponsorShip</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="payments" data-id="payment" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-exchange" viewBox="0 0 16 16">
                                <path d="M0 5a5.002 5.002 0 0 0 4.027 4.905 6.46 6.46 0 0 1 .544-2.073C3.695 7.536 3.132 6.864 3 5.91h-.5v-.426h.466V5.05c0-.046 0-.093.004-.135H2.5v-.427h.511C3.236 3.24 4.213 2.5 5.681 2.5c.316 0 .59.031.819.085v.733a3.46 3.46 0 0 0-.815-.082c-.919 0-1.538.466-1.734 1.252h1.917v.427h-1.98c-.003.046-.003.097-.003.147v.422h1.983v.427H3.93c.118.602.468 1.03 1.005 1.229a6.5 6.5 0 0 1 4.97-3.113A5.002 5.002 0 0 0 0 5zm16 5.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0zm-7.75 1.322c.069.835.746 1.485 1.964 1.562V14h.54v-.62c1.259-.086 1.996-.74 1.996-1.69 0-.865-.563-1.31-1.57-1.54l-.426-.1V8.374c.54.06.884.347.966.745h.948c-.07-.804-.779-1.433-1.914-1.502V7h-.54v.629c-1.076.103-1.808.732-1.808 1.622 0 .787.544 1.288 1.45 1.493l.358.085v1.78c-.554-.08-.92-.376-1.003-.787H8.25zm1.96-1.895c-.532-.12-.82-.364-.82-.732 0-.41.311-.719.824-.809v1.54h-.005zm.622 1.044c.645.145.943.38.943.796 0 .474-.37.8-1.02.86v-1.674l.077.018z" />
                            </svg>
                            <span class="ml-3">Payments</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="payment" data-parentid="payments" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>PaymentList" class="sub-menu" data-parent="payments">
                                    <i class="las la-minus"></i><span>Payment List</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="users" data-id="user1" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
                                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                            </svg>
                            <span class="ml-3">Employee</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="user1" data-parentid="users" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>IdentifyEmployeeList" class="sub-menu" data-parent="users">
                                    <i class="las la-minus"></i><span>Identify Employee List</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>EmployeeListManage" class="sub-menu" data-parent="users">
                                    <i class="las la-minus"></i><span>Employee List Manage</span>
                                </a>
                            </li>
                        </ul>
                    </li>




                    <li class=" pl">
                        <a id="follows" data-id="follow" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <i class="fas fa-wifi"></i>
                            <span class="ml-3">Connection</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="follow" data-parentid="follows" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>MyFollower" class="sub-menu" data-parent="follows">
                                    <i class="las la-minus"></i><span>Follower</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>MyFollowing" class="sub-menu" data-parent="follows">
                                    <i class="las la-minus"></i><span>Following</span>
                                </a>
                            </li>
                        </ul>
                    </li>


                    <li class=" pl">
                        <a id="shops" data-id="shop" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                        <i class="bi bi-bag-check-fill"></i>
                            <span class="ml-3">Shopping</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="shop" data-parentid="shops" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>BusinessShopDealsList" class="sub-menu" data-parent="shops">
                                    <i class="las la-minus"></i><span>Deals</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>BusinessShopCouponsList" class="sub-menu" data-parent="shops">
                                    <i class="las la-minus"></i><span>Coupons</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class=" pl">
                        <a id="messages" data-id="message" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chat-right-dots-fill" viewBox="0 0 16 16">
                                <path d="M16 2a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h9.586a1 1 0 0 1 .707.293l2.853 2.853a.5.5 0 0 0 .854-.353V2zM5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
                            </svg>
                            <span class="ml-3">Message</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="message" data-parentid="messages" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>MyInbox" class="sub-menu" data-parent="messages">
                                    <i class="las la-minus"></i><span>Inbox</span>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?= $URL_Domain ?>MySend" class="sub-menu" data-parent="messages">
                                    <i class="las la-minus"></i><span>Send</span>
                                </a>
                            </li>
                        </ul>
                    </li>


                    <li class=" pl">
                        <a id="supports" data-id="support" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                        <i class="fas fa-headset"></i>
                            <span class="ml-3">Support</span>
                            <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                        </a>
                        <ul id="support" data-parentid="supports" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                            <li class="">
                                <a href="<?= $URL_Domain ?>SupportList" class="sub-menu" data-parent="supports">
                                    <i class="las la-minus"></i><span>Support List</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>

            <div class="pt-5 pb-2"></div>
        </div>
        <div class="scrollbar-track scrollbar-track-x" style="display: none;">
            <div class="scrollbar-thumb scrollbar-thumb-x" style="width: 274px; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
        <div class="scrollbar-track scrollbar-track-y" style="display: block;">
            <div class="scrollbar-thumb scrollbar-thumb-y" style="height: 60.6143px; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
    </div>
</div>