<div class="modal fade bd-example-modal-lg" id="ModalAdd" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Banner Price</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="addFrm">

                <?php include_once $VIEW_PATH_INCLUDE . "Admin/modal/BannerItem.phtml"; ?>


                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Price:</label>
                        <input type="text" autocomplete="off" class="form-control min-radus " id="price" name="price">
                    </div>



                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-editid="" data-id="ModalAdd" id="btnSave" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>