<div class="modal fade bd-example-modal-lg" id="ModalAddPresent" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">Add percent</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmPercent">

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Percent:</label>
                        <input type="number" autocomplete="off" class="form-control min-radus " name="percent" id="percent">
                        <input type="text" hidden id="deals_id">
                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-id="ModalAddPresent" id="btnModalAddPresent" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>