<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Section:</label>
    <select class="form-control min-radus " id="section" name="section"></select>
</div>

<div class="mb-3 " id="more_cat"></div>

<div class="mb-3">
    <button type="button" id="add_more_cat" data-id="more_cat" class="btn btn-glass" hidden>Add More</button>
    <!-- <button type="button" id="reset_cat" data-id="more_cat" class="btn btn-danger m-1">Remove All</button> -->

</div>


<div class="mb-3" id="programs">
    <label for="recipient-name" class="col-form-label"> Program:</label>
    <select class="form-control min-radus " id="proof_id" name="proof_id"></select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Type:</label>
    <select class="form-control min-radus " id="type" name="type">
        <option value=""></option>
        <option value="big">Big</option>
        <!-- <option value="small">Small</option> -->
    </select>
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Calculate type:</label>
    <select name="calculate_type" id="calculate_type" class="form-control">
        <option value=""></option>
        <option value="click">Click</option>
        <option value="show">Show</option>
    </select>
</div>