<div class="modal fade bd-example-modal-lg" id="ModalClearing" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Clearing </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
            
                <form id="frmClearing">


                    <input type="text" value="" hidden name="idSearch" id="idSearch">
                    <div class="mb-3">
                        <input accept=".png, .jpg, .jpeg, .pdf,.doc, .docx" type="file" name="main_image" id="main_image" multiple class="fileInputs">

                    </div>

                </form>

            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-id="ModalClearing" id="addClearing" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>