<div class="modal fade bd-example-modal-lg" id="ModalAdd" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> New Lottery </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="addFrm">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Type:</label>
                        <select name="type" id="type" class="form-control">
                            <option value=""></option>
                            <?php include_once $VIEW_PATH_INCLUDE . "Admin/modal/LotteryType.phtml"; ?>
                        </select>
                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-id="ModalAdd" id="btnModalAdd" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>