  <div class="mb-3">
      <label for="recipient-name" class="col-form-label">Search Prize:</label>
      <select style="width: 100%" class="input-white min-radus  prize-search select-css" multiple name="prize_id" id="prize_id<?=$edit?>">

      </select>

  </div>

  <div class="mb-3">
      <label for="recipient-name" class="col-form-label"> Date of Prize donation:</label>
      <input type="date" class="form-control" name="date_donation" id="date_donation<?=$edit?>">

  </div>
  <div class="mb-3">
      <label for="recipient-name" class="col-form-label"> Numbers:</label>
      <input type="number" class="form-control" name="number_donations" id="number_donations<?=$edit?>">

  </div>