<div class="modal fade bd-example-modal-lg" id="ModalImageGallery" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">  Image Gallery</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <input type="text" name="idSearchImage" id="idSearchImage" hidden>
                <div class="row" id="images">

                </div>
                <div class="row">
                    <div class="col-md-12">
                    <div class="mb-3">
                    <input type="file" accept=".png, .jpg, .jpeg"  multiple name="file_image_gallery" id="file_image_gallery" class="fileinputs">

                </div>
                    </div>
                </div>
               
            </div>
            <div class="modal-footer-glass modal-footer">
                <button data-id="ModalImageGallery" id="btnaddimagegallery" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>