<div class="modal fade bd-example-modal-lg" id="ModalViewEvent" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Information of Product</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="row text-center">
                    <div class="col-md-12  mb-2 p-1" id="imgEvent">
                        
                    </div>
                    <div class="col-md-12 text-center mb-1" id="titleEvent">

                    </div>
                    <div class="col-md-12 p-1 mb-1">
                        <p id="descriptionEvent"></p>
                    </div>
                    <div class="col-md-12 p-1 mb-1" id="category_id_view">
                        
                    </div>
                    <div class="col-md-12 p-1 mb-1" id="Links">
                        
                    </div>

                    <div class="col-md-12 p-1 mb-1" id="prise">
                        
                    </div>
                </div>
   
            </div>
            <div class="modal-footer-glass modal-footer">
            </div>
        </div>
    </div>
</div>