<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Seen :</label>
    <label class="radiobox">Nobody
        <input type="radio" value="0" checked name="is_public" id="is_public">
        <span class="chmr"></span>
    </label>
    <label class="radiobox">My followers
        <input type="radio" value="1" name="is_public" id="is_public2">
        <span class="chmr"></span>
    </label>
    <label class="radiobox">All
        <input type="radio" value="2" name="is_public" id="is_public3">
        <span class="chmr"></span>
    </label>
</div>