<div id="profSidemenu" class="sidepanel  ">
    <div class="closebtn" id="closeNavProf">×</div>
    <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="bi bi-house-fill"></i> </div>
        <div class="tag-side-menu">
            <a href="<?=$URL_Domain?>home">Home</a>
        </div>
    </div>

    <!-- <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="bi bi-person-badge-fill"></i> </div>
        <div class="tag-side-menu">
            <a href="Profile">profile</a>
        </div>
    </div> -->

    <!-- <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="bi bi-bell-fill"></i></div>
        <div class="tag-side-menu">
            <a href="#">Notification</a>
        </div>
    </div> -->
<!-- 
    <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="bi bi-envelope-fill"></i> </div>
        <div class="tag-side-menu">
            <a href="#">Message</a>
        </div>
    </div> -->

    <div class="side-menu-header">
        <div class="icon-side-menu-header"><i class="fas fa-sign-out-alt"></i> </div>
        <div class="tag-side-menu">
            <a href="<?=$URL_Domain?>LogOutAdmin">Log out</a>
        </div>
    </div>

</div>