<link rel="stylesheet" href="<?= $VIEW_PATH ?>css/UserDashboard/Layout/SideMenu.css?v=<?= $VERSION ?>">
<?php
$menu = $permissions->data->menu;
$list = $permissions->data->list;
$menus = [];
$lists = [];
foreach ($menu as $m) {
    array_push($menus, $m->menu);
}
foreach ($list as $l) {
    array_push($lists, $l->list);
}

?>
<div id="sideBar" class="iq-sidebar   sidebar-default ">

    <div class="data-scrollbar" data-scroll="1" data-scrollbar="true" tabindex="-1">
        <div class="scroll-content">
            <nav class="iq-sidebar-menu">
                <ul id="iq-sidebar-toggle" class="iq-menu">
                    <li class="active pl">
                        <a href="<?= $URL_Domain ?>AdminDashboard" class="svg-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" width="20" height="20">
                                <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path>
                            </svg>
                            <span class="ml-3"> Dashboard</span>
                        </a>
                    </li>


                    <?php if (in_array("productsp", $menus)) { ?>
                        <li class=" pl">
                            <a id="productsp" data-id="products" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16">
                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                                </svg>
                                <span class="ml-3">Product</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="products" data-parentid="productsp" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("pr1", $lists)) { ?>
                                    <li class="" id="pr1">
                                        <a href="<?= $URL_Domain ?>ProductListAdmin" class="sub-menu" data-parent="productsp">
                                            <i class="las la-minus"></i><span>Product List</span>
                                        </a>
                                    </li>
                                <?php } ?>
                                <?php if (in_array("pr2", $lists)) { ?>
                                    <li class="" id="pr2">
                                        <a href="<?= $URL_Domain ?>MyProductAdmin" class="sub-menu" data-parent="productsp">
                                            <i class="las la-minus"></i><span>My Products</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>


                    <?php if (in_array("prizesp", $menus)) { ?>
                        <li class=" pl">
                            <a id="prizesp" data-id="prizes" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gift" viewBox="0 0 16 16">
                                    <path d="M3 2.5a2.5 2.5 0 0 1 5 0 2.5 2.5 0 0 1 5 0v.006c0 .07 0 .27-.038.494H15a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 1 14.5V7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h2.038A2.968 2.968 0 0 1 3 2.506V2.5zm1.068.5H7v-.5a1.5 1.5 0 1 0-3 0c0 .085.002.274.045.43a.522.522 0 0 0 .023.07zM9 3h2.932a.56.56 0 0 0 .023-.07c.043-.156.045-.345.045-.43a1.5 1.5 0 0 0-3 0V3zM1 4v2h6V4H1zm8 0v2h6V4H9zm5 3H9v8h4.5a.5.5 0 0 0 .5-.5V7zm-7 8V7H2v7.5a.5.5 0 0 0 .5.5H7z" />
                                </svg>
                                <span class="ml-3">Prize</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="prizes" data-parentid="prizesp" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("e1", $lists)) { ?>
                                    <li class="" id="e1">
                                        <a href="<?= $URL_Domain ?>PrizeListAdmin" class="sub-menu" data-parent="prizesp">
                                            <i class="las la-minus"></i><span>Prize List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("e2", $lists)) { ?>
                                    <li class="" id="e2">
                                        <a href="<?= $URL_Domain ?>MyPrizeAdmin" class="sub-menu" data-parent="prizesp">
                                            <i class="las la-minus"></i><span>My Prize</span>
                                        </a>
                                    </li>
                                <?php } ?>


                                <?php if (in_array("e3", $lists)) { ?>
                                    <li class="" id="e3">
                                        <a href="<?= $URL_Domain ?>SetPrizeAdmin" class="sub-menu" data-parent="prizesp">
                                            <i class="las la-minus"></i><span>Set Prize</span>
                                        </a>
                                    </li>
                                <?php } ?>

                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("couponp", $menus)) { ?>
                        <li class=" pl">
                            <a id="couponp" data-id="coupon" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16">
                                    <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
                                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
                                </svg>
                                <span class="ml-3">Coupon</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="coupon" data-parentid="couponp" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("fo1", $lists)) { ?>
                                    <li class="" id="fo1">
                                        <a href="<?= $URL_Domain ?>CouponListAdmin" class="sub-menu" data-parent="couponp">
                                            <i class="las la-minus"></i><span>Coupon List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("fo2", $lists)) { ?>
                                    <li class="" id="fo2">
                                        <a href="<?= $URL_Domain ?>MyCouponAdmin" class="sub-menu" data-parent="couponp">
                                            <i class="las la-minus"></i><span>My Coupon</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("dealsP", $menus)) { ?>
                        <li class=" pl">
                            <a id="dealsP" data-id="deals" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z" />
                                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z" />
                                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z" />
                                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z" />
                                </svg>
                                <span class="ml-3">Deals</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="deals" data-parentid="dealsP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("de1", $lists)) { ?>
                                    <li class="" id="de1">
                                        <a href="<?= $URL_Domain ?>DealsListAdmin" class="sub-menu" data-parent="dealsP">
                                            <i class="las la-minus"></i><span>Deals List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("de2", $lists)) { ?>
                                    <li class="" id="de2">
                                        <a href="<?= $URL_Domain ?>MyDealsAdmin" class="sub-menu" data-parent="dealsP">
                                            <i class="las la-minus"></i><span>My Deals</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("jobP", $menus)) { ?>
                        <li class=" pl">
                            <a id="jobP" data-id="jobs" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-briefcase" viewBox="0 0 16 16">
                                    <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v8A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1h-3zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5zm1.886 6.914L15 7.151V12.5a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5V7.15l6.614 1.764a1.5 1.5 0 0 0 .772 0zM1.5 4h13a.5.5 0 0 1 .5.5v1.616L8.129 7.948a.5.5 0 0 1-.258 0L1 6.116V4.5a.5.5 0 0 1 .5-.5z" />
                                </svg>
                                <span class="ml-3">Jobs</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="jobs" data-parentid="jobP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("j1", $lists)) { ?>
                                    <li class="" id="j1">
                                        <a href="<?= $URL_Domain ?>JobListAdmin" class="sub-menu" data-parent="jobP">
                                            <i class="las la-minus"></i><span>Job List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("j2", $lists)) { ?>
                                    <li class="" id="j2">
                                        <a href="<?= $URL_Domain ?>MyJobAdmin" class="sub-menu" data-parent="jobP">
                                            <i class="las la-minus"></i><span>My Job</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("programP", $menus)) { ?>
                        <li class=" pl">
                            <a id="programP" data-id="program" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-film" viewBox="0 0 16 16">
                                    <path d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0v6h8V1H4zm8 8H4v6h8V9zM1 1v2h2V1H1zm2 3H1v2h2V4zM1 7v2h2V7H1zm2 3H1v2h2v-2zm-2 3v2h2v-2H1zM15 1h-2v2h2V1zm-2 3v2h2V4h-2zm2 3h-2v2h2V7zm-2 3v2h2v-2h-2zm2 3h-2v2h2v-2z" />
                                </svg>
                                <span class="ml-3">Program</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="program" data-parentid="programP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("po1", $lists)) { ?>
                                    <li class="" id="po1">
                                        <a href="<?= $URL_Domain ?>MyProgramAdmin" class="sub-menu" data-parent="programP">
                                            <i class="las la-minus"></i><span>My Program List</span>
                                        </a>
                                    </li>
                                <?php } ?>


                            </ul>
                        </li>
                    <?php } ?>


                    <?php if (in_array("reportm", $menus)) { ?>
                        <li class=" pl">

                            <a id="reportm" data-id="reports" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-lg" viewBox="0 0 16 16">
                                    <path d="M6.002 14a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm.195-12.01a1.81 1.81 0 1 1 3.602 0l-.701 7.015a1.105 1.105 0 0 1-2.2 0l-.7-7.015z" />
                                </svg>
                                <span class="ml-3">Report</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="reports" data-parentid="reportm" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("report1", $lists)) { ?>
                                    <li class="" id="report1">
                                        <a href="<?= $URL_Domain ?>ReportList" class="sub-menu" data-parent="reportm">
                                            <i class="las la-minus"></i><span>Report List</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("userm", $menus)) { ?>
                        <li class=" pl">

                            <a id="userm" data-id="users" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                    <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
                                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                                </svg>
                                <span class="ml-3">Users</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="users" data-parentid="userm" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("user1", $lists)) { ?>
                                    <li class="" id="user1">
                                        <a href="<?= $URL_Domain ?>UserManager" class="sub-menu" data-parent="userm">
                                            <i class="las la-minus"></i><span>User Manager</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>


                    <?php if (in_array("teams", $menus)) { ?>
                        <li class=" pl">

                            <a id="teams" data-id="team" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                    <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
                                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                                </svg>
                                <span class="ml-3">Teams</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="team" data-parentid="teams" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("team1", $lists)) { ?>
                                    <li class="" id="team1">
                                        <a href="<?= $URL_Domain ?>teamManager" class="sub-menu" data-parent="teams">
                                            <i class="las la-minus"></i><span>Team Manager</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("usermb", $menus)) { ?>
                        <li class=" pl">

                            <a id="usermb" data-id="usersb" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                    <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
                                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                                </svg>
                                <span class="ml-3">Business Users</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="usersb" data-parentid="usermb" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("userb1", $lists)) { ?>
                                    <li class="" id="userb1">
                                        <a href="<?= $URL_Domain ?>BusinessUserManager" class="sub-menu" data-parent="usermb">
                                            <i class="las la-minus"></i><span>Business User Manager</span>
                                        </a>
                                    </li>
                                <?php } ?>
                                <?php if (in_array("userb2", $lists)) { ?>
                                    <li class="" id="userb2">
                                        <a href="<?= $URL_Domain ?>BusinessTransfer" class="sub-menu" data-parent="usermb">
                                            <i class="las la-minus"></i><span>Transfer </span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("userb3", $lists)) { ?>
                                    <li class="" id="userb3">
                                        <a href="<?= $URL_Domain ?>ConfirmVerify" class="sub-menu" data-parent="usermb">
                                            <i class="las la-minus"></i><span>Confirm Verify </span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("comments", $menus)) { ?>
                        <li class=" pl">

                            <a id="comments" data-id="comment" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chat-dots" viewBox="0 0 16 16">
                                    <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                                    <path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z" />
                                </svg>
                                <span class="ml-3">Comments</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="comment" data-parentid="comments" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("com1", $lists)) { ?>
                                    <li class="" id="com1">
                                        <a href="<?= $URL_Domain ?>ProductComment" class="sub-menu" data-parent="comments">
                                            <i class="las la-minus"></i><span>Products</span>
                                        </a>
                                    </li>
                                <?php } ?>
                                <?php if (in_array("com2", $lists)) { ?>
                                    <li class="" id="com2">
                                        <a href="<?= $URL_Domain ?>CouponComment" class="sub-menu" data-parent="comments">
                                            <i class="las la-minus"></i><span>Coupon </span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("com3", $lists)) { ?>
                                    <li class="" id="com3">
                                        <a href="<?= $URL_Domain ?>DealsComment" class="sub-menu" data-parent="comments">
                                            <i class="las la-minus"></i><span>Deals </span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("com4", $lists)) { ?>
                                    <li class="" id="com4">
                                        <a href="<?= $URL_Domain ?>ProgramComment" class="sub-menu" data-parent="comments">
                                            <i class="las la-minus"></i><span>Program </span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("com5", $lists)) { ?>
                                    <li class="" id="com5">
                                        <a href="<?= $URL_Domain ?>ProfileComment" class="sub-menu" data-parent="comments">
                                            <i class="las la-minus"></i><span>Profiles </span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>


                    <?php if (in_array("claims", $menus)) { ?>
                        <li class=" pl">

                            <a id="claims" data-id="claim" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-shield-fill-exclamation" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 0c-.69 0-1.843.265-2.928.56-1.11.3-2.229.655-2.887.87a1.54 1.54 0 0 0-1.044 1.262c-.596 4.477.787 7.795 2.465 9.99a11.777 11.777 0 0 0 2.517 2.453c.386.273.744.482 1.048.625.28.132.581.24.829.24s.548-.108.829-.24a7.159 7.159 0 0 0 1.048-.625 11.775 11.775 0 0 0 2.517-2.453c1.678-2.195 3.061-5.513 2.465-9.99a1.541 1.541 0 0 0-1.044-1.263 62.467 62.467 0 0 0-2.887-.87C9.843.266 8.69 0 8 0zm-.55 8.502L7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0zM8.002 12a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
                                </svg>
                                <span class="ml-3">Claims</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="claim" data-parentid="claims" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("claim1", $lists)) { ?>
                                    <li class="" id="claim1">
                                        <a href="<?= $URL_Domain ?>ClaimListAdmin" class="sub-menu" data-parent="claims">
                                            <i class="las la-minus"></i><span>Claims</span>
                                        </a>
                                    </li>
                                <?php } ?>

                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("adM", $menus)) { ?>
                        <li class=" pl">

                            <a id="adM" data-id="adU" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-badge-ad" viewBox="0 0 16 16">
                                    <path d="m3.7 11 .47-1.542h2.004L6.644 11h1.261L5.901 5.001H4.513L2.5 11h1.2zm1.503-4.852.734 2.426H4.416l.734-2.426h.053zm4.759.128c-1.059 0-1.753.765-1.753 2.043v.695c0 1.279.685 2.043 1.74 2.043.677 0 1.222-.33 1.367-.804h.057V11h1.138V4.685h-1.16v2.36h-.053c-.18-.475-.68-.77-1.336-.77zm.387.923c.58 0 1.002.44 1.002 1.138v.602c0 .76-.396 1.2-.984 1.2-.598 0-.972-.449-.972-1.248v-.453c0-.795.37-1.24.954-1.24z" />
                                    <path d="M14 3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h12zM2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2z" />
                                </svg>
                                <span class="ml-3">Advertise with us</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="adU" data-parentid="adM" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("ad1", $lists)) { ?>
                                    <li class="" id="ad1">
                                        <a href="<?= $URL_Domain ?>AdSettingList" class="sub-menu" data-parent="adM">
                                            <i class="las la-minus"></i><span>Setting</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("ad2", $lists)) { ?>
                                    <li class="" id="ad2">
                                        <a href="<?= $URL_Domain ?>SponsorshipList" class="sub-menu" data-parent="adM">
                                            <i class="las la-minus"></i><span>Sponsorship List</span>
                                        </a>
                                    </li>
                                <?php } ?>


                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("bannerP", $menus)) { ?>
                        <li class=" pl">
                            <a id="bannerP" data-id="banner" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-card-image" viewBox="0 0 16 16">
                                    <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                                    <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54A.505.505 0 0 1 1 12.5v-9a.5.5 0 0 1 .5-.5h13z" />
                                </svg>
                                <span class="ml-3">Banner Order</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="banner" data-parentid="bannerP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("ban1", $lists)) { ?>
                                    <li class="" id="ban1">
                                        <a href="<?= $URL_Domain ?>BusinessBannerList" class="sub-menu" data-parent="bannerP">
                                            <i class="las la-minus"></i><span>Business Banner List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("ban2", $lists)) { ?>
                                    <li class="" id="ban2">
                                        <a href="<?= $URL_Domain ?>UserBannerList" class="sub-menu" data-parent="bannerP">
                                            <i class="las la-minus"></i><span>User Banner List</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("supportP", $menus)) { ?>
                        <li class=" pl">
                            <a id="supportP" data-id="support" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <i class="fas fa-headset"></i>
                                <span class="ml-3">Support</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="support" data-parentid="supportP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("sp1", $lists)) { ?>
                                    <li class="" id="sp1">
                                        <a href="<?= $URL_Domain ?>SupportAdminList" class="sub-menu" data-parent="supportP">
                                            <i class="las la-minus"></i><span>Support List</span>
                                        </a>
                                    </li>
                                <?php } ?>


                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("countryM", $menus)) { ?>
                        <li class=" pl">

                            <a id="countryM" data-id="countryU" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
                                    <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z" />
                                    <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                </svg>
                                <span class="ml-3">Country</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="countryU" data-parentid="countryM" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("country1", $lists)) { ?>
                                    <li class="" id="country1">
                                        <a href="<?= $URL_Domain ?>CountryList" class="sub-menu" data-parent="countryM">
                                            <i class="las la-minus"></i><span>Country List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("country2", $lists)) { ?>
                                    <li class="" id="country2">
                                        <a href="<?= $URL_Domain ?>ProvinceList" class="sub-menu" data-parent="countryM">
                                            <i class="las la-minus"></i><span>Province List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("country3", $lists)) { ?>
                                    <li class="" id="country3">
                                        <a href="<?= $URL_Domain ?>CityList" class="sub-menu" data-parent="countryM">
                                            <i class="las la-minus"></i><span>City List</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>


                    <?php if (in_array("accountingP", $menus)) { ?>
                        <li class=" pl">

                            <a id="accountingP" data-id="accountM" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z" />
                                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z" />
                                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z" />
                                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z" />
                                </svg>
                                <span class="ml-3">Accounting</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>

                            <ul id="accountM" data-parentid="accountingP" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("acc1", $lists)) { ?>
                                    <li class="" id="acc1">
                                        <a href="<?= $URL_Domain ?>DealsAccountList" class="sub-menu" data-parent="accountingP">
                                            <i class="las la-minus"></i><span>Deals List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("acc2", $lists)) { ?>
                                    <li class="" id="acc2">
                                        <a href="<?= $URL_Domain ?>DealsClearedList" class="sub-menu" data-parent="accountingP">
                                            <i class="las la-minus"></i><span>Deals Cleared List</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if (in_array("settings", $menus)) { ?>
                        <li class=" pl">
                            <a id="settings" data-id="proofs" href="javascript:void(0)" class="collapsed" data-toggle="collapse" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                                    <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
                                </svg>
                                <span class="ml-3">Setting</span>
                                <i class="bi bi-chevron-right iq-arrow-right arrow-active"></i>

                            </a>
                            <ul id="proofs" data-parentid="settings" class="iq-submenu hide" data-parent="#iq-sidebar-toggle">
                                <?php if (in_array("setting1", $lists)) { ?>
                                    <li class="" id="setting1">
                                        <a href="<?= $URL_Domain ?>ProofList" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i><span>Proof List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting2", $lists)) { ?>
                                    <li class="" id="setting2">
                                        <a href="<?= $URL_Domain ?>CategoryList" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i><span>Category List</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting3", $lists)) { ?>
                                    <li class="" id="setting3">
                                        <a href="<?= $URL_Domain ?>AdminManager" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i><span>Admin Manager</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting4", $lists)) { ?>
                                    <li class="" id="setting4">
                                        <a href="<?= $URL_Domain ?>Sliders" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Sliders</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting5", $lists)) { ?>
                                    <li class="" id="setting5">
                                        <a href="<?= $URL_Domain ?>SetPoints" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Set points</span>
                                        </a>
                                    </li>
                                <?php } ?>


                                <?php if (in_array("setting6", $lists)) { ?>
                                    <li class="" id="setting6">
                                        <a href="<?= $URL_Domain ?>Lottery" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Lottery</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting7", $lists)) { ?>
                                    <li class="" id="setting7">
                                        <a href="<?= $URL_Domain ?>HelpList" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Help</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting8", $lists)) { ?>
                                    <li class="" id="setting8">
                                        <a href="<?= $URL_Domain ?>AdvertisePrice" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Advertise Price</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting9", $lists)) { ?>
                                    <li class="" id="setting9">
                                        <a href="<?= $URL_Domain ?>BannerPrice" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Banner Price</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting10", $lists)) { ?>
                                    <li class="" id="setting10">
                                        <a href="<?= $URL_Domain ?>Seo" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Seo</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting11", $lists)) { ?>
                                    <li class="" id="setting11">
                                        <a href="<?= $URL_Domain ?>Studio" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>studio </span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting12", $lists)) { ?>
                                    <li class="" id="setting12">
                                        <a href="<?= $URL_Domain ?>AboutUs" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>About us </span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting13", $lists)) { ?>
                                    <li class="" id="setting13">
                                        <a href="<?= $URL_Domain ?>PriceSetting" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span> Setting</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting14", $lists)) { ?>
                                    <li class="" id="setting14">
                                        <a href="<?= $URL_Domain ?>MyDiscountAdmin" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Discount Code</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                <?php if (in_array("setting15", $lists)) { ?>
                                    <li class="" id="setting15">
                                        <a href="<?= $URL_Domain ?>ContactWithUsList" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Contact With Us</span>
                                        </a>
                                    </li>
                                <?php } ?>

                                
                                <?php if (in_array("setting16", $lists)) { ?>
                                    <li class="" id="setting16">
                                        <a href="<?= $URL_Domain ?>Announcement" class="sub-menu" data-parent="settings">
                                            <i class="las la-minus"></i> <span>Announcement</span>
                                        </a>
                                    </li>
                                <?php } ?>

                            </ul>
                        </li>
                    <?php } ?>



                </ul>
            </nav>

            <div class="pt-5 pb-2"></div>
        </div>
        <div class="scrollbar-track scrollbar-track-x" style="display: none;">
            <div class="scrollbar-thumb scrollbar-thumb-x" style="width: 274px; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
        <div class="scrollbar-track scrollbar-track-y" style="display: block;">
            <div class="scrollbar-thumb scrollbar-thumb-y" style="height: 60.6143px; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
    </div>
</div>

<script type="module" src="<?= $VIEW_PATH ?>js/UserDashboard/Layout/SideMenu.js?v=<?= $VERSION ?>"></script>