<?php
include($VIEW_PATH_INCLUDE . "BusinessDashboard/Product/modal/ViewData.phtml");
include_once $VIEW_PATH_INCLUDE . "UserDashboard/Common/Modal/Category.phtml";
include_once $VIEW_PATH_ADMIN_INCLUDE . "modal/AddNote.phtml";
include_once $VIEW_PATH_ADMIN_INCLUDE . "Confirm/View5.phtml";

//include_once $VIEW_PATH_ADMIN_INCLUDE . "Common/modal/SendToTop.phtml";
include_once $VIEW_PATH_ADMIN_INCLUDE . "Common/modal/SendToHome.phtml";
include_once $VIEW_PATH_INCLUDE."BusinessDashboard/modal/AddToTop.phtml";

?>
