<div class="row ">


    <div class="covers">

        <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Image</th>
                    <th>Section</th>
                    <!-- <th>Calculate_type</th>
                    <th>Type</th> -->
                    <th>Link</th>
                    <th>Category</th>
                    <th>Program</th>
                    <!-- <th>Payment</th> -->
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>

        </table>
    </div>
</div>