<div class="row ">
    <div class="accordion accordion-flush m-top mb-5" id="accordionFlushExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" style="background: #e3dfdf91;" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                    <i class="bi bi-search"></i>
                </button>
            </h2>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="covers mb-3">
                    <form id="searchfrm">
                        <div class="row">

                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label">ID:</label>
                                    <input type="text" autocomplete="off" class="form-control min-radus " id="idSearchs" name="idSearch">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label">Title:</label>
                                    <input type="text" autocomplete="off" class="form-control min-radus " id="titlese">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label"> Name:</label>
                                    <input type="text" autocomplete="off" class="form-control min-radus " id="name">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label">User Email:</label>
                                    <input type="text" autocomplete="off" class="form-control min-radus " id="email">
                                </div>
                            </div>


                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label">Date From:</label>
                                    <input type="date" autocomplete="off" class="form-control min-radus " id="created_at_from">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label">Date To:</label>
                                    <input type="date" autocomplete="off" class="form-control min-radus " id="created_at_to">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label">Status:</label>
                                    <select id="admin_confirm" class="form-control ">
                                        <option value=""></option>
                                        <option value="0">pending</option>
                                        <option value="1">Accepted</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="recipient-name" class="col-form-label">Disabled:</label>
                                    <select id="trash" class="form-control ">
                                        <option value=""></option>
                                        <option value="0" selected>No</option>
                                        <option value="1">Yes</option>
                                    </select>
                                </div>
                            </div>


                            <div class="col-md-12 mb-2 text-center">
                                <button type="button" id="searchbtn" class="btn btn-prim btn-lg">
                                    <i class="bi bi-search mr-2"></i> Search
                                </button>
                                <button id="reset" type="button" class="btn  btn-lg">
                                    Reset
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


        </div>
    </div>




    <div class="covers">

        <table width="100%" class="table table-striped table-hover dt-responsive display dataTable" id="m_table_1">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>User Name</th>
                    <th>Category</th>
                    <th>Type</th>
                    <th>Level</th>
                    <th>Skill</th>
                    <th>Exprience</th>
                    <th>Salary</th>
                    <th>Gender</th>
                    <th>Benefit</th>
                    <th>Description</th>
                    <th>Post Date</th>
                    <th>Status</th>
                    <th>Home Show</th>
                    <th>Action</th>
                </tr>
            </thead>

        </table>
    </div>
</div>