<div class="modal fade bd-example-modal-lg" id="modalLanguage" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">Language</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmlang">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Language :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="language" id="language">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Proficiency:</label>
                        <select style="width: 100%" class="input-white min-radus  select-css" name="proficiency" id="proficiency">
                            <option value="Please select">
                                Please select
                            </option>
                            <option value="Elementary proficiency">
                                Elementary proficiency
                            </option>
                            <option value="Limited working proficiency">
                                Limited working proficiency
                            </option>
                            <option value="Full professional proficiency">
                                Full professional proficiency
                            </option>
                            <option value="Professional working proficiency">
                                Professional working proficiency
                            </option>
                            <option value="Native or bilingual proficiency">
                                Native or bilingual proficiency
                            </option>
                        </select>
                    </div>
                    <?php
                   // include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../privacyAccess/privacy.phtml";
                    include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../delete/remove.phtml";

                    ?>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-editid="" data-edit="false" data-id="modalLanguage" id="btnlang" class="btn  btn-glass">Save</button>
            </div>
        </div>
    </div>
</div>