<div class="modal fade bd-example-modal-lg" id="modalOrganization" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">Organization</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmorg">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Name :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="organization_name" id="organization_name">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Position held :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="position" id="position">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Associated with (experience):</label>
                        <select style="width: 100%" class="input-white min-radus  select-css" name="organization_experience_id" id="organization_experience_id">
                       
                        </select>

                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Start Date :</label>
                        <input type="date" autocomplete="off" class="input-white min-radus " name="organization_start_date" id="organization_start_date">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">End Date :</label>
                        <input type="date" autocomplete="off" class="input-white min-radus " name="organization_end_date" id="organization_end_date">
                    </div>

                    <div class="mb-3">
                        <label class="chboxs">Membership ongoing
                            <input type="checkbox" id="organization_now" name="organization_now" value="1">
                            <span class="checkmark"></span>
                        </label>
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label"> Description :</label>
                        <textarea rows="5" autocomplete="off" class="input-white min-radus " name="organization_description" id="organization_description"></textarea>
                    </div>
                    <?php
                  //  include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../privacyAccess/privacy.phtml";
                    include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../delete/remove.phtml";

                    ?>
                </form>

            </div>

            <div class="modal-footer-glass modal-footer">
                <button data-edit="false" data-editid="" data-id="modalOrganization" id="btnorg" type="button" class="btn  btn-glass">Save</button>
            </div>
        </div>
    </div>
</div>