<div class="modal fade bd-example-modal-lg" id="modalPublication" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">publication</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmpub">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Title  :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="title_publication" id="title_publication">
                    </div>


                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Publication/Publisher :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="publisher" id="publisher">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Publication date :</label>
                        <input type="date" autocomplete="off" class="input-white min-radus " name="publication_date" id="publication_date">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Author :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="author" id="author">
                    </div>
                    
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Publication URL :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="publication_url" id="publication_url">
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Description :</label>
                        <textarea rows="5" autocomplete="off" class="input-white min-radus " name="publication_description" id="publication_description"></textarea>
                    </div>
                    <?php
                   // include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../privacyAccess/privacy.phtml";
                    include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../delete/remove.phtml";

                    ?>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-editid="" data-edit="false" data-id="modalPublication" id="frmpubbtn" class="btn  btn-glass">Save</button>
            </div>
        </div>
    </div>
</div>