<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Title:</label>
    <input type="text" autocomplete="off" class="form-control  " id="title<?= $edit ?>" name="title">
</div>



<div class="mb-3 row" id="more_team">
</div>

<div class="mb-3">
    <button type="button" id="add_more_teams" data-id="more_team" class="btn btn-glass">Add More Team</button>
</div>



<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Date From:</label>
    <input type="date" autocomplete="off" class="form-control  " id="date_from<?= $edit ?>" name="date_from">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Time From:</label>
    <input type="time" autocomplete="off" class="form-control  " id="time_from<?= $edit ?>" name="time_from">
</div>

<div class="mb-5">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Date To:</label>
    <input type="date" autocomplete="off" class="form-control  " id="date_to<?= $edit ?>" name="date_to">
</div>

<div class="mb-3">
    <label for="recipient-name" class="col-form-label"> Time To:</label>
    <input type="time" autocomplete="off" class="form-control  " name="time_to" id="time_to<?= $edit ?>">
</div>



<div class="mb-3 row" id="more_guest">
</div>

<div class="mb-3">
    <button type="button" id="add_more_guest" data-id="more_guest" class="btn btn-glass">Add More Guest</button>
</div>


<div class="mb-3">
    <label for="recipient-name" class="col-form-label">Description:</label>
    <textarea rows="5" class="form-control  " name="description" id="description<?= $edit ?>"></textarea>
</div>


