<?php

   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Remove.phtml";
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/AddNewBanner.phtml";
   include_once $VIEW_PATH_INCLUDE."BusinessDashboard/Product/modal/EditImage.phtml";
   include_once $VIEW_PATH_INCLUDE."UserDashboard/Common/Modal/Category.phtml";

?>
<div class="covers">
<input type="text" hidden id="creator_types" value="<?=$data['creator_type']?>">
    <div class="covers m-top mb-3">
        <div class="row">
            <div class="col-md-12 mb-2">
                <small id="addNewBtn" class="btn btn-prim btn-lg ">
                    <i class="bi bi-plus-lg mr-2"></i> Add Banner
                </small>
            </div>

      
        </div>
    </div>
    <table width="100%" class="table table-striped table-hover dt-responsive display datatable" id="m_table_1">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Section</th>
                <th>Calculate Type</th>
                <th>Type</th>
                <th>Link</th>
                <th>Category</th>
                <th>Program</th>
                <th>Price</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>