<div class="modal fade bd-example-modal-lg" id="ChooseType" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">My Types</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                    <div class="mb-3">
                        <input type="text" name="idSearch" id="idSearch" hidden>
                        <label for="recipient-name" class="col-form-label">Type:</label>
                        <select name="type" id="type" class="form-control"></select>

                    </div>

               
             
                    
            </div>

            <div class="modal-footer-glass modal-footer">
            <button data-edit="false" id="btnSaveChoose" type="button" class="btn  btn-glass">Save</button>

            </div>
        </div>
    </div>
</div>