<div class="modal fade bd-example-modal-lg" id="ModalType" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Types</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Title:</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " id="name" name="name">
                    </div>

                    <div class="row">
                        <div class="col-md-12 text-center">
                        <button data-edit="false" id="btnSave" type="button" class="btn  btn-glass">Save</button>

                        </div>

                        <div class="col-md-12 mt-5 row" id="resultType"></div>
                    </div>
             
                    
            </div>

            <div class="modal-footer-glass modal-footer">

            </div>
        </div>
    </div>
</div>