<div class="modal fade bd-example-modal-lg" id="modalPatent" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">patent</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frnpatent">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Title :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="title_patent" id="title_patent">
                    </div>

                    <!-- country -->
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Office Country:</label>
                        <select style="width: 100%" class="input-white min-radus select2 select-css" id="patent_country_id" name="patent_country_id">

                        </select>

                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Patent or application number :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="number" id="number">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Status :</label>
                        <label class="radiobox">Patent Issued
                            <input type="radio" value="Issued" name="status" id="status">
                            <span class="chmr"></span>
                        </label>
                        <label class="radiobox">Patent Pending
                            <input type="radio" value="Pending" name="status" id="status2">
                            <span class="chmr"></span>
                        </label>
            
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Issue date :</label>
                        <input type="date" autocomplete="off" class="input-white min-radus " name="issue_date" id="issue_date">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Publication URL :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="patent_url" id="patent_url">
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Description :</label>
                        <textarea rows="5" autocomplete="off" class="input-white min-radus " name="patent_description" id="patent_description"></textarea>
                    </div>
                    <?php
                    include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../privacyAccess/privacy.phtml";
                    include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../delete/remove.phtml";

                    ?>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-editid="" data-edit="false" data-id="modalPatent" id="patentbtn" class="btn  btn-glass">Save</button>
            </div>
        </div>
    </div>
</div>