<div class="modal fade bd-example-modal-lg" id="modalProject" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">Project</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmProject">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Name :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="project_name" id="project_name">
                    </div>


                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Associated with (experience):</label>
                        <select style="width: 100%" class="input-white min-radus select2 select-css" name="project_experience_id" id="project_experience_id">
                            <option value="">...</option>
                       
                        </select>

                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Creator :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="creator" id="creator">
                    </div>

       
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Start Date :</label>
                        <input type="date" autocomplete="off" class="input-white min-radus " name="project_start_date" id="project_start_date">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">End Date :</label>
                        <input type="date" autocomplete="off" class="input-white min-radus " name="project_end_date" id="project_end_date">
                    </div>

                    <div class="mb-3">
                        <label class="chboxs">I am currently working in this role
                            <input type="checkbox" value="1" name="project_now" id="project_now">
                            <span class="checkmark"></span>
                        </label>
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Project URL :</label>
                        <input type="text" autocomplete="off" class="input-white min-radus " name="project_url" id="project_url">
                    </div>

                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Project Description :</label>
                        <textarea rows="5" type="text" class="input-white min-radus " name="project_description" id="project_description"></textarea>
                    </div>
                    <?php
                    include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../privacyAccess/privacy.phtml";
                    include dirname(__FILE__) . DIRECTORY_SEPARATOR  . "../delete/remove.phtml";

                    ?>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-editid="" data-edit="false" data-id="modalProject" id="projectbtn" class="btn  btn-glass">Save</button>
            </div>
        </div>
    </div>
</div>