
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Title:</label>
        <input type="text" autocomplete="off" class="form-control min-radus " name="title" id="title<?=$edit?>">
    </div>

    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Description:</label>
        <textarea  class="form-control min-radus " name="descriptions" id="descriptions<?=$edit?>"></textarea>
    </div>