
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Title:</label>
        <input type="text" autocomplete="off" class="input-white min-radus " name="title" id="title<?=$edit?>">
    </div>


    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">link:</label>
        <input type="text" autocomplete="off" class="input-white min-radus " name="link" id="link<?=$edit?>">
    </div>
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Description:</label>
        <textarea rows="5" autocomplete="off" class="input-white min-radus " name="description" id="description<?=$edit?>"></textarea>
    </div>