
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Name:</label>
        <input type="text" autocomplete="off" class="input-white min-radus " name="name" id="name<?=$edit?>">
    </div>

    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Username:</label>
        <input type="text" autocomplete="off" class="input-white min-radus " name="username" id="username<?=$edit?>">
    </div>

    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Password:</label>
        <input type="text" autocomplete="off" class="input-white min-radus " name="password" id="password<?=$edit?>">
    </div>
