    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Choose timezone:</label>
        <select class="form-control select2 " style="width: 100%;" name="timezone" id="timezone<?= $edit ?>"></select>
    </div>
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">First Name:</label>
        <input type="text" class="input-white min-radus " name="fname" id="fname<?= $edit ?>">
    </div>
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Last Name:</label>
        <input type="text" class="input-white min-radus " name="lname" id="lname<?= $edit ?>">
    </div>
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Email:</label>
        <input type="text" class="input-white min-radus " name="email" id="email<?= $edit ?>">
    </div>
    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Password:</label>
        <input type="text" class="input-white min-radus " name="password" id="password<?= $edit ?>">
    </div>



    <!-- link start -->
    <div class="mb-3 row" id="more_link<?= $edit ?>">
        <div class="col-md-4">
            <label for="recipient-name" class="col-form-label">Link type:</label>
            <select id="ltype<?= $edit ?>1" class="form-control min-radus select-css ">
                <option value=""></option>
                <option value="web">webSite</option>
                <option value="socialMedia">Social Media</option>

            </select>
        </div>
        <div class="col-md-4">
            <label for="recipient-name" class="col-form-label">Link Title:</label>
            <input id="ltitle<?= $edit ?>1" type="text" autocomplete="off" class="form-control min-radus ">
        </div>
        <div class="col-md-4">
            <label for="recipient-name" class="col-form-label">Link Address:</label>
            <input id="ltag<?= $edit ?>1" type="text" autocomplete="off" class="form-control min-radus ">
        </div>


    </div>

    <div class="mb-3">
        <button type="button" id="add_more_links<?= $edit ?>" data-id="more_link<?= $edit ?>" class="btn btn-glass">Add More</button>
    </div>
    <!-- link end -->


    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">About:</label>
        <textarea class="input-white min-radus " name="about" id="about<?= $edit ?>"></textarea>
    </div>

    <div class="mb-3">
        <label for="recipient-name" class="col-form-label">Public:</label>
        <select name="is_public" id="public<?= $edit ?>" class="form-control">
            <option value=""></option>
            <option value="0">No</option>
            <option value="1">Yes</option>
        </select>
    </div>