<div class="modal fade bd-example-modal-lg" id="modalEditInfo" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel">Edit your info</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmEditInfo">
                    <?php
                    include $VIEW_PATH_INCLUDE . "BusinessDashboard/User/ProfileModal/Item.phtml";
                    ?>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button"  data-id="modalEditInfo" id="editInfoBtn" class="btn  btn-glass">Save</button>
            </div>
        </div>
    </div>
</div>