<div class="modal fade bd-example-modal-lg" id="modalEditAbout" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered ">
        <div class="modal-content modal-dialog-glass">
            <div class="modal-header modal-header-glass">
                <h5 class="modal-title" id="exampleModalLabel"> Edit About  </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form id="frmAbout">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Summary:</label>
                        <textarea rows="5" autocomplete="off" class="input-white min-radus" id="about" name="about"></textarea>
                    </div>
                </form>
            </div>

            <div class="modal-footer-glass modal-footer">
                <button type="button" data-editid="" data-edit="false" data-id="modalEditAbout" id="aboutBtn" class="btn  btn-glass">Save</button>
             
            </div>
        </div>
    </div>
</div>