<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-card-image" viewBox="0 0 16 16">
        <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
        <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54A.505.505 0 0 1 1 12.5v-9a.5.5 0 0 1 .5-.5h13z" />
    </svg>
    <span class="ml-3">Banner Order</span>

</div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Business Banner List
        <input type="checkbox" id="ch_ban1" name="listm" value="ban1,bannerP">
        <span class="checkmark"></span>
    </label>

</div>
<div class="col-md-4 mt-3 ">

    <label class="chboxs ">Confirm
        <input type="checkbox" id="ban1_confirm" name="modul" value="confirm,ban1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs col-md-3">Reject
        <input type="checkbox" name="modul" id="ban1_reject" value="reject,ban1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Note
        <input type="checkbox" name="modul" id="ban1_note" value="note,ban1">
        <span class="checkmark"></span>
    </label>
</div>
<div class="col-md-5 mt-3">
  
    <!-- <label class="chboxs ">View
        <input type="checkbox" name="modul" id="ban1_view" value="view,ban1">
        <span class="checkmark"></span>
    </label>  -->
</div>

<hr>
<div class="col-md-3 mt-3">

    <label class="chboxs">User Banner List
        <input type="checkbox" id="ch_ban2" name="listm" value="ban2,bannerP">
        <span class="checkmark"></span>
    </label>

</div>
<div class="col-md-4 mt-3 ">

    <label class="chboxs ">Confirm
        <input type="checkbox" id="ban2_confirm" name="modul" value="confirm,ban2">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs col-md-3">Reject
        <input type="checkbox" name="modul" id="ban2_reject" value="reject,ban2">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Note
        <input type="checkbox" name="modul" id="ban2_note" value="note,ban2">
        <span class="checkmark"></span>
    </label>
</div>
<div class="col-md-5 mt-3">
  
    <!-- <label class="chboxs ">View
        <input type="checkbox" name="modul" id="ban2_view" value="view,ban2">
        <span class="checkmark"></span>
    </label>  -->
</div>
