<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
        <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
        <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
        <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
    </svg>
    <span class="ml-3">Business Users</span>

</div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Business User Manager
        <input type="checkbox" name="listm" id="ch_userb1" value="userb1,usermb">
        <span class="checkmark"></span>
    </label>

</div>

<div class="col-md-5 mt-3">
    <label class="chboxs ">Send To Top List
        <input type="checkbox" name="modul" id="userb1_top" value="top,userb1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Send To Home
        <input type="checkbox" id="userb1_home" name="modul" value="home,userb1">
        <span class="checkmark"></span>
    </label>

</div>
<hr>

<div class="col-md-3 mt-3">

    <label class="chboxs">Transfer
        <input type="checkbox" name="listm" id="ch_userb2" value="userb2,usermb">
        <span class="checkmark"></span>
    </label>

</div>

<div class="col-md-3 mt-3">

    <label class="chboxs">Confirm Verify
        <input type="checkbox" name="listm" id="ch_userb3" value="userb3,usermb">
        <span class="checkmark"></span>
    </label>

</div>
