<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-briefcase" viewBox="0 0 16 16">
        <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v8A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1h-3zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5zm1.886 6.914L15 7.151V12.5a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5V7.15l6.614 1.764a1.5 1.5 0 0 0 .772 0zM1.5 4h13a.5.5 0 0 1 .5.5v1.616L8.129 7.948a.5.5 0 0 1-.258 0L1 6.116V4.5a.5.5 0 0 1 .5-.5z" />
    </svg>
    <span class="ml-3">Job</span>

</div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Job List
        <input type="checkbox" id="ch_j1" name="listm" value="j1,jobP">
        <span class="checkmark"></span>
    </label>

</div>
<div class="col-md-4 mt-3 ">

    <label class="chboxs ">Confirm
        <input type="checkbox" id="j1_confirm" name="modul" value="confirm,j1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs col-md-3">Reject
        <input type="checkbox" name="modul" id="j1_reject" value="reject,j1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Note
        <input type="checkbox" name="modul" id="j1_note" value="note,j1">
        <span class="checkmark"></span>
    </label>
</div>
<div class="col-md-5 mt-3">
    <label class="chboxs ">Send To Top List
        <input type="checkbox" name="modul" id="j1_top" value="top,j1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Send To Home
        <input type="checkbox" name="modul" id="j1_home" value="home,j1">
        <span class="checkmark"></span>
    </label>


    <!-- <label class="chboxs ">View
        <input type="checkbox" name="modul" id="j1_view" value="view,j1">
        <span class="checkmark"></span>
    </label>  -->
</div>

<hr>
<div class="col-md-3 mt-3">

    <label class="chboxs">My Job
        <input type="checkbox" name="listm" id="ch_j2" value="j2,jobP">
        <span class="checkmark"></span>
    </label>

</div>