<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gift" viewBox="0 0 16 16">
        <path d="M3 2.5a2.5 2.5 0 0 1 5 0 2.5 2.5 0 0 1 5 0v.006c0 .07 0 .27-.038.494H15a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 1 14.5V7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h2.038A2.968 2.968 0 0 1 3 2.506V2.5zm1.068.5H7v-.5a1.5 1.5 0 1 0-3 0c0 .085.002.274.045.43a.522.522 0 0 0 .023.07zM9 3h2.932a.56.56 0 0 0 .023-.07c.043-.156.045-.345.045-.43a1.5 1.5 0 0 0-3 0V3zM1 4v2h6V4H1zm8 0v2h6V4H9zm5 3H9v8h4.5a.5.5 0 0 0 .5-.5V7zm-7 8V7H2v7.5a.5.5 0 0 0 .5.5H7z" />
    </svg>
    <span class="ml-3">Prize</span>

</div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Prize List
        <input type="checkbox" id="ch_e1" name="listm" value="e1,prizesp">
        <span class="checkmark"></span>
    </label>

</div>
<div class="col-md-4 mt-3 ">

    <label class="chboxs ">Confirm
        <input type="checkbox" id="e1_confirm" name="modul" value="confirm,e1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs col-md-3">Reject
        <input type="checkbox" id="e1_reject" name="modul" value="reject,e1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Note
        <input type="checkbox" id="e1_note" name="modul" value="note,e1">
        <span class="checkmark"></span>
    </label>
</div>
<div class="col-md-5 mt-3">
     <label class="chboxs ">Send To Top List
        <input type="checkbox" id="e1_top" name="modul" value="top,e1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Send To Home
        <input type="checkbox" id="e1_home" name="modul" value="home,e1">
        <span class="checkmark"></span>
    </label> 
    <label class="chboxs ">View
        <input type="checkbox" id="e1_view" name="modul" value="view,e1">
        <span class="checkmark"></span>
    </label>
</div>

<hr>
<div class="col-md-3 mt-3">

    <label class="chboxs">My Prize
        <input type="checkbox" id="ch_e2" name="listm" value="e2,prizesp">
        <span class="checkmark"></span>
    </label>

</div>

<div></div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Set Prize
        <input type="checkbox" id="ch_e3" name="listm" value="e3,prizesp">
        <span class="checkmark"></span>
    </label>

</div>