<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16">
        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
    </svg>
    <span class="ml-3">Product</span>

</div>
<div class="col-md-3 mt-3">

    <label class="chboxs">Product List
        <input type="checkbox" id="ch_pr1" name="listm" value="pr1,productsp">
        <span class="checkmark"></span>
    </label>

</div>
<div class="col-md-4 mt-3 ">

    <label class="chboxs ">Confirm
        <input type="checkbox" id="pr1_confirm" name="modul" value="confirm,pr1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs col-md-3">Reject
        <input type="checkbox" id="pr1_reject" name="modul" value="reject,pr1">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs ">Note
        <input type="checkbox" id="pr1_note" name="modul" value="note,pr1">
        <span class="checkmark"></span>
    </label>
</div>
<div class="col-md-5 mt-3">
    <label class="chboxs ">Send To Top List
        <input type="checkbox" id="pr1_top" name="modul" value="top,pr1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">Send To Home
        <input type="checkbox" id="pr1_home" name="modul" value="home,pr1">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs ">View
        <input type="checkbox" id="pr1_view" name="modul" value="view,pr1">
        <span class="checkmark"></span>
    </label>
</div>

<hr>
<div class="col-md-3 mt-3">

    <label class="chboxs">My Products
        <input type="checkbox" id="ch_pr2" name="listm" value="pr2,productsp">
        <span class="checkmark"></span>
    </label>

</div>