<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
        <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
    </svg>
    <span class="ml-3">Setting</span>

</div>

<div class="col-md-4 mt-3">

    <label class="chboxs">Proof List
        <input type="checkbox" id="ch_setting1" name="listm" value="setting1,settings">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs">Category List
        <input type="checkbox" name="listm" id="ch_setting2" value="setting2,settings">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs">Admin Manager
        <input type="checkbox" name="listm" id="ch_setting3" value="setting3,settings">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs">Sliders
        <input type="checkbox" name="listm" id="ch_setting4" value="setting4,settings">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs">Set points
        <input type="checkbox" name="listm" id="ch_setting5" value="setting5,settings">
        <span class="checkmark"></span>
    </label>


    <label class="chboxs">Lottery
        <input type="checkbox" name="listm" id="ch_setting6" value="setting6,settings">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs">Help
        <input type="checkbox" name="listm" id="ch_setting7" value="setting7,settings">
        <span class="checkmark"></span>
    </label>


    <label class="chboxs">Advertise Price
        <input type="checkbox" name="listm" id="ch_setting8" value="setting8,settings">
        <span class="checkmark"></span>
    </label>


</div>
<div class="col-md-5 mt-3">
    <label class="chboxs">Banner Price
        <input type="checkbox" name="listm" id="ch_setting9" value="setting9,settings">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs">Seo
        <input type="checkbox" name="listm" id="ch_setting10" value="setting10,settings">
        <span class="checkmark"></span>
    </label>
    <label class="chboxs">Studio
        <input type="checkbox" name="listm" id="ch_setting11" value="setting11,settings">
        <span class="checkmark"></span>
    </label>

    
    <label class="chboxs">About us
        <input type="checkbox" name="listm" id="ch_setting12" value="setting12,settings">
        <span class="checkmark"></span>
    </label>
       
    <label class="chboxs">Price Setting
        <input type="checkbox" name="listm" id="ch_setting13" value="setting13,settings">
        <span class="checkmark"></span>
    </label>

    <label class="chboxs">Discount Code
        <input type="checkbox" name="listm" id="ch_setting14" value="setting14,settings">
        <span class="checkmark"></span>
    </label>

    
    <label class="chboxs">Contact With Us
        <input type="checkbox" name="listm" id="ch_setting15" value="setting15,settings">
        <span class="checkmark"></span>
    </label>

    
    <label class="chboxs">Announcement
        <input type="checkbox" name="listm" id="ch_setting16" value="setting16,settings">
        <span class="checkmark"></span>
    </label>
</div>